#ifndef QA_TARGET_KEYS_H
#define QA_TARGET_KEYS_H
#include "qa/strings.h"

/* Known engine fields bind once in the session name table; authored custom
 * fields use their admitted qa_string_id through the same accessors. */
#define QA_TARGET_KEY_LIST(X) \
    X(____, "/\\:") \
    X(_COLOR, "_color") \
    X(ACCEL, "accel") \
    X(ACHIEVEMENT, "achievement") \
    X(ADDON_FROZENDAMAGEABLE, "addon.frozenDamageable") \
    X(ALPHA, "alpha") \
    X(AMMO_ROCKETS1, "ammo_rockets1") \
    X(ANGLE, "angle") \
    X(ANGLES, "angles") \
    X(ATTACK_FINISHED, "attack_finished") \
    X(ATTENUATION, "attenuation") \
    X(CATEGORY, "category") \
    X(CLASSNAME, "classname") \
    X(CNT, "cnt") \
    X(COMBATTARGET, "combattarget") \
    X(COUNT, "count") \
    X(COUNTER_STATE, "counter_state") \
    X(CTF_BASE, "ctf.base") \
    X(CTF_LASTCAPTURE, "ctf.lastCapture") \
    X(CTF_LASTCAPTURETEAM, "ctf.lastCaptureTeam") \
    X(CTF_RETURN, "ctf.return") \
    X(CTF_RUNE, "ctf.rune") \
    X(CTF_RUNESSPAWNED, "ctf.runesSpawned") \
    X(CTF_FLAGS, "ctf_flags") \
    X(CTF_FLAGSINCE, "ctf_flagsince") \
    X(CTF_KILLED, "ctf_killed") \
    X(CTF_LASTFRAGGEDCARRIER, "ctf_lastfraggedcarrier") \
    X(CTF_LASTHURTCARRIER, "ctf_lasthurtcarrier") \
    X(CTF_LASTRETURNEDFLAG, "ctf_lastreturnedflag") \
    X(CURRENTAMMO, "currentammo") \
    X(DAMAGE, "damage") \
    X(DEATHTARGET, "deathtarget") \
    X(DECEL, "decel") \
    X(DELAY, "delay") \
    X(DISTANCE, "distance") \
    X(DMG, "dmg") \
    X(EVENT, "event") \
    X(EYE_POSITION, "eye_position") \
    X(FADE_END_DIST, "fade_end_dist") \
    X(FADE_START_DIST, "fade_start_dist") \
    X(FLY_SOUND, "fly_sound") \
    X(FOG_COLOR, "fog_color") \
    X(FOG_COLOR_OFF, "fog_color_off") \
    X(FOG_DENSITY, "fog_density") \
    X(FOG_DENSITY_OFF, "fog_density_off") \
    X(FOG_INFO_ENTITY, "fog_info_entity") \
    X(FOG_SKY_FACTOR, "fog_sky_factor") \
    X(FOG_SKY_FACTOR_OFF, "fog_sky_factor_off") \
    X(FRAGS, "frags") \
    X(GOAL_STATE, "goal_state") \
    X(GOALS, "goals") \
    X(GRAVITY, "gravity") \
    X(GROUP, "group") \
    X(HACKFLAGS, "hackflags") \
    X(HEALTH, "health") \
    X(HEALTHTARGET, "healthtarget") \
    X(HEIGHT, "height") \
    X(HEIGHTFOG_DENSITY, "heightfog_density") \
    X(HEIGHTFOG_DENSITY_OFF, "heightfog_density_off") \
    X(HEIGHTFOG_END_COLOR, "heightfog_end_color") \
    X(HEIGHTFOG_END_COLOR_OFF, "heightfog_end_color_off") \
    X(HEIGHTFOG_END_DIST, "heightfog_end_dist") \
    X(HEIGHTFOG_END_DIST_OFF, "heightfog_end_dist_off") \
    X(HEIGHTFOG_FALLOFF, "heightfog_falloff") \
    X(HEIGHTFOG_FALLOFF_OFF, "heightfog_falloff_off") \
    X(HEIGHTFOG_START_COLOR, "heightfog_start_color") \
    X(HEIGHTFOG_START_COLOR_OFF, "heightfog_start_color_off") \
    X(HEIGHTFOG_START_DIST, "heightfog_start_dist") \
    X(HEIGHTFOG_START_DIST_OFF, "heightfog_start_dist_off") \
    X(HUB_MAP, "hub_map") \
    X(IMAGE, "image") \
    X(IS_FROZEN, "is_frozen") \
    X(ITEM, "item") \
    X(ITEMS, "items") \
    X(ITEMTARGET, "itemtarget") \
    X(KILLTARGET, "killtarget") \
    X(LIP, "lip") \
    X(LTRAILLASTUSED, "ltrailLastUsed") \
    X(MANGLE, "mangle") \
    X(MAP, "map") \
    X(MASS, "mass") \
    X(MAXPITCH, "maxpitch") \
    X(MAXS, "maxs") \
    X(MAXYAW, "maxyaw") \
    X(MDL, "mdl") \
    X(MESSAGE, "message") \
    X(MINPITCH, "minpitch") \
    X(MINS, "mins") \
    X(MINYAW, "minyaw") \
    X(MODEL, "model") \
    X(MODEL2, "model2") \
    X(MONSTER_SLOTS, "monster_slots") \
    X(MOVEDIR, "movedir") \
    X(NOISE, "noise") \
    X(NOISE1, "noise1") \
    X(NOISE_END, "noise_end") \
    X(NOISE_MIDDLE, "noise_middle") \
    X(NOISE_START, "noise_start") \
    X(OLDORIGIN, "oldorigin") \
    X(ORIGIN, "origin") \
    X(PAIN_FINISHED, "pain_finished") \
    X(PATH, "path") \
    X(PATHTARGET, "pathtarget") \
    X(PAUSETIME, "pausetime") \
    X(RADIUS, "radius") \
    X(RANDOM, "random") \
    X(REINFORCEMENTS, "reinforcements") \
    X(RGBA, "rgba") \
    X(ROGUE_ACTORSTAGE, "rogue:actorStage") \
    X(ROGUE_CUTSCENE_RUNNING, "rogue:cutscene_running") \
    X(ROGUE_EARTHQUAKE_ACTIVE, "rogue:earthquake_active") \
    X(ROGUE_EARTHQUAKE_INTENSITY, "rogue:earthquake_intensity") \
    X(ROGUE_ELVBUTNDIR, "rogue:elvButnDir") \
    X(ROGUE_ENDING_STARTED, "rogue:ending_started") \
    X(ROGUE_IMPACTVELOCITY, "rogue:impactVelocity") \
    X(ROGUE_NEXTTEAMUPDTIME, "rogue:nextteamupdtime") \
    X(ROGUE_RUNES_SPAWNED, "rogue:runes_spawned") \
    X(ROLL, "roll") \
    X(ROTATE, "rotate") \
    X(RUNE, "rune") \
    X(SCALE, "scale") \
    X(SHADOWLIGHTCONEANGLE, "shadowlightconeangle") \
    X(SHADOWLIGHTENDFADEDISTANCE, "shadowlightendfadedistance") \
    X(SHADOWLIGHTINTENSITY, "shadowlightintensity") \
    X(SHADOWLIGHTRADIUS, "shadowlightradius") \
    X(SHADOWLIGHTRESOLUTION, "shadowlightresolution") \
    X(SHADOWLIGHTSTARTFADEDISTANCE, "shadowlightstartfadedistance") \
    X(SHADOWLIGHTSTYLE, "shadowlightstyle") \
    X(SHADOWLIGHTSTYLETARGET, "shadowlightstyletarget") \
    X(SKINNUM, "skinnum") \
    X(SKY, "sky") \
    X(SKYAUTOROTATE, "skyautorotate") \
    X(SKYAXIS, "skyaxis") \
    X(SKYROTATE, "skyrotate") \
    X(SOUNDS, "sounds") \
    X(SPAWNCLASSNAME, "spawnclassname") \
    X(SPAWNFLAGS, "spawnflags") \
    X(SPAWNFUNCTION, "spawnfunction") \
    X(SPAWNMULTI, "spawnmulti") \
    X(SPAWNSILENT, "spawnsilent") \
    X(SPEED, "speed") \
    X(STATE, "state") \
    X(STEAM, "steam") \
    X(STOREDNEXTTHINK, "storednextthink") \
    X(STYLE, "style") \
    X(SUICIDE_COUNT, "suicide_count") \
    X(SUPER_TIME, "super_time") \
    X(TAG_FRAGS, "tag_frags") \
    X(TAG_MESSAGE_TIME, "tag_message_time") \
    X(TARGET, "target") \
    X(TARGETNAME, "targetname") \
    X(TEAM, "team") \
    X(V_ANGLE, "v_angle") \
    X(VELOCITY, "velocity") \
    X(VIEW_OFS, "view_ofs") \
    X(VISION_CONE, "vision_cone") \
    X(VOLUME, "volume") \
    X(WAIT, "wait") \
    X(WEAPON, "weapon") \
    X(WETSUIT_TIME, "wetsuit_time")

typedef enum qa_target_key {
#define QA_TARGET_KEY_ENUM(key, text) QA_TARGET_KEY_##key,
    QA_TARGET_KEY_LIST(QA_TARGET_KEY_ENUM)
#undef QA_TARGET_KEY_ENUM
    QA_TARGET_KEY_TOTAL
} qa_target_key;
bool qa_targets_bind_field_keys(qa_strings *, qa_string_id keys[QA_TARGET_KEY_TOTAL], qa_error *);
#endif
