#ifndef QA_FRONTEND_Q2_EFFECT_MODELS_H
#define QA_FRONTEND_Q2_EFFECT_MODELS_H
typedef enum q2fx_model {
    Q2FX_EXPLODE, Q2FX_SMOKE, Q2FX_FLASH, Q2FX_PARASITE, Q2FX_CABLE,
    Q2FX_ROCKET, Q2FX_BFG, Q2FX_LIGHTNING, Q2FX_HEAT, Q2FX_BIG,
    Q2FX_MUZZLE_MACHINE, Q2FX_MUZZLE_SSHOTGUN, Q2FX_MUZZLE_SHOTGUN,
    Q2FX_MUZZLE_ROCKET, Q2FX_MUZZLE_RAIL, Q2FX_MUZZLE_LAUNCH,
    Q2FX_MUZZLE_ETF, Q2FX_MUZZLE_DIST, Q2FX_MUZZLE_BOOMER,
    Q2FX_MUZZLE_BLAST, Q2FX_MUZZLE_BFG, Q2FX_MUZZLE_BEAM,
    Q2FX_MODEL_COUNT
} q2fx_model;
extern const char *const q2fx_model_paths[Q2FX_MODEL_COUNT];
#endif
