#ifndef QA_FRONTEND_VIDEO_MODES_GENERATED_H
#define QA_FRONTEND_VIDEO_MODES_GENERATED_H
#include <stdint.h>
/* Generated by tools/generate_video_modes.py from data/unified-cvars.csv,
 * quake-2/linux/vid_so.c and quake-iii-arena/code/renderer/tr_init.c. */
typedef struct frontend_video_mode_size { uint32_t width,height; } frontend_video_mode_size;
static const frontend_video_mode_size frontend_video_modes[]={
    {320,240},
    {400,300},
    {512,384},
    {640,480},
    {800,600},
    {960,720},
    {1024,768},
    {1152,864},
    {1280,1024},
    {1600,1200},
    {2048,1536},
    {856,480},
};
#define FRONTEND_Q2_VIDEO_MODE_COUNT 10u
#define FRONTEND_VIDEO_MODE_NAME "r_mode"
#define FRONTEND_VIDEO_FULLSCREEN_MEMBER "vid_fullscreen"
static const char *const frontend_q2_video_members[]={"gl_mode","sw_mode"};
#endif
