#include "internal.h"

#define HUMAN {{-16, -16, -24}, {16, 16, 40}}
#define LARGE {{-32, -32, -24}, {32, 32, 64}}
static const q1_species species[] = {
    {QA_Q1_OLDONE,
     "monster_oldone_new",
     Q1_NAME_RESOURCE_PROGS_OLDONE_MDL, Q1_NAME_COUNT,Q1_NAME_CLASS_EMPTY,
     "oldnew_idle1",
     "oldnew_idle1",
     "oldnew_walk1",
     NULL,
     12000,
     -INFINITY,
     {{-128, -128, -24}, {128, 128, 256}},
     0,
     false},
    {QA_Q1_BOSS,
     "monster_boss_final",
     Q1_NAME_RESOURCE_PROGS_BOSS_MDL, Q1_NAME_COUNT,Q1_NAME_CLASS_EMPTY,
     "boss_final_idle1",
     "boss_final_idle1",
     "boss_final_missile1",
     "boss_final_missile1",
     12000,
     -INFINITY,
     {{-128, -128, -24}, {128, 128, 256}},
     0,
     false},
    {QA_Q1_ARMY,
     "monster_ghost",
     Q1_NAME_RESOURCE_PROGS_PLAYER_MDL, Q1_NAME_COUNT,Q1_NAME_CLASS_EMPTY,
     "ghost_stand1",
     "ghost_run1",
     "ghost_run1",
     NULL,
     10,
     -INFINITY,
     {{-16, -16, -24}, {16, 16, 32}},
     0,
     false},
    {QA_Q1_WIZARD, "monster_orb", Q1_NAME_RESOURCE_PROGS_TELEPORTER_EYE_BLINK_MDL, Q1_NAME_COUNT,Q1_NAME_CLASS_EMPTY, "orb_stand1",
     "orb_walk1", "orb_run1", "orb_fast1", 300, -INFINITY, LARGE, QA_PHYSICS_FLYING, false},
    {QA_Q1_ZOMBIE,
     "monster_szombie",
     Q1_NAME_RESOURCE_PROGS_ZOMBIE_MDL, Q1_NAME_COUNT,Q1_NAME_CLASS_EMPTY,
     "szombie_stand1",
     "szombie_walk1",
     "szombie_run1",
     NULL,
     60,
     -INFINITY,
     {{-16, -16, -24}, {16, 16, 32}},
     0,
     true},
    {QA_Q1_SHAMBLER, "monster_super_shambler", Q1_NAME_RESOURCE_PROGS_SHAMBLER_BLOOD_MDL, Q1_NAME_RESOURCE_PROGS_H_SHAMS_MDL,Q1_NAME_CLASS_EMPTY,
     "supsham_stand1", "supsham_walk1", "supsham_run1", "supsham_melee", 2000, -60, LARGE, 0, true},
    {QA_Q1_HELLKNIGHT, "monster_ranged_knight", Q1_NAME_RESOURCE_PROGS_RKNIGHT_MDL, Q1_NAME_RESOURCE_PROGS_H_HELLKN_MDL,Q1_NAME_CLASS_EMPTY,
     "rknight_stand1", "rknight_walk1", "rknight_run", "rknight_magic", 250, -40, HUMAN, 0, false},
    {QA_Q1_ARMY, "monster_army_infected", Q1_NAME_RESOURCE_PROGS_SOLDIER_MDL, Q1_NAME_RESOURCE_PROGS_H_GUARD_MDL,Q1_NAME_RESOURCE_SOLDIER_SIGHT1_WAV,
     "infected_army_stand1", "infected_army_walk1", "infected_army_run1", "infected_army_atk1", 30,
     -35, HUMAN, 0, false},
    {QA_Q1_KNIGHT, "monster_knight_infected", Q1_NAME_RESOURCE_PROGS_KNIGHT_MDL, Q1_NAME_RESOURCE_PROGS_H_KNIGHT_MDL,Q1_NAME_RESOURCE_KNIGHT_KSIGHT_WAV,
     "knight_stand1", "knight_walk1", "knight_run1", NULL, 75, -40, HUMAN, 0, true},
    {QA_Q1_ENFORCER, "monster_enforcer_infected", Q1_NAME_RESOURCE_PROGS_ENFORCER_MDL, Q1_NAME_RESOURCE_PROGS_H_MEGA_MDL,Q1_NAME_RESOURCE_ENFORCER_SIGHT1_WAV, "enf_stand1", "enf_walk1", "enf_run1", "enf_atk1", 80, -35, LARGE, 0,
     false},
    {QA_Q1_HELLKNIGHT, "monster_hell_knight_infected", Q1_NAME_RESOURCE_PROGS_HKNIGHT_MDL, Q1_NAME_RESOURCE_PROGS_H_HELLKN_MDL,Q1_NAME_RESOURCE_HKNIGHT_SIGHT1_WAV, "hknight_stand1", "hknight_walk1", "hknight_run1", "hknight_magicc1",
     250, -40, LARGE, 0, true},
    {QA_Q1_DOG, "monster_demodog", Q1_NAME_RESOURCE_PROGS_DOG_EXPLOSIVE_MDL, Q1_NAME_RESOURCE_PROGS_H_DOG_MDL,Q1_NAME_RESOURCE_DOG_DSIGHT_WAV,
     "demodog_stand1", "demodog_walk1", "demodog_run1", "demodog_leap1", 25, -35, LARGE, 0, true},
    {QA_Q1_ARMY, "monster_army", Q1_NAME_RESOURCE_PROGS_SOLDIER_MDL, Q1_NAME_RESOURCE_PROGS_H_GUARD_MDL,Q1_NAME_RESOURCE_SOLDIER_SIGHT1_WAV,
     "army_stand1", "army_walk1", "army_run1", "army_atk1", 30, -35, HUMAN, 0, false},
    {QA_Q1_DOG,
     "monster_dog",
     Q1_NAME_RESOURCE_PROGS_DOG_MDL, Q1_NAME_RESOURCE_PROGS_H_DOG_MDL,Q1_NAME_RESOURCE_DOG_DSIGHT_WAV,
     "dog_stand1",
     "dog_walk1",
     "dog_run1",
     "dog_leap1",
     25,
     -35,
     {{-32, -32, -24}, {32, 32, 40}},
     0,
     true},
    {QA_Q1_KNIGHT, "monster_knight", Q1_NAME_RESOURCE_PROGS_KNIGHT_MDL, Q1_NAME_RESOURCE_PROGS_H_KNIGHT_MDL,Q1_NAME_RESOURCE_KNIGHT_KSIGHT_WAV,
     "knight_stand1", "knight_walk1", "knight_run1", NULL, 75, -40, HUMAN, 0, true},
    {QA_Q1_ENFORCER, "monster_enforcer", Q1_NAME_RESOURCE_PROGS_ENFORCER_MDL, Q1_NAME_RESOURCE_PROGS_H_MEGA_MDL,Q1_NAME_RESOURCE_ENFORCER_SIGHT1_WAV,
     "enf_stand1", "enf_walk1", "enf_run1", "enf_atk1", 80, -35, HUMAN, 0, false},
    {QA_Q1_DEMON, "monster_demon1", Q1_NAME_RESOURCE_PROGS_DEMON_MDL, Q1_NAME_RESOURCE_PROGS_H_DEMON_MDL,Q1_NAME_RESOURCE_DEMON_SIGHT2_WAV,
     "demon1_stand1", "demon1_walk1", "demon1_run1", "demon1_jump1", 300, -80, LARGE, 0, true},
    {QA_Q1_OGRE, "monster_ogre", Q1_NAME_RESOURCE_PROGS_OGRE_MDL, Q1_NAME_RESOURCE_PROGS_H_OGRE_MDL,Q1_NAME_RESOURCE_OGRE_OGWAKE_WAV, "ogre_stand1",
     "ogre_walk1", "ogre_run1", "ogre_nail1", 200, -80, LARGE, 0, true},
    {QA_Q1_OGRE, "monster_ogre_marksman", Q1_NAME_RESOURCE_PROGS_OGRE_MDL, Q1_NAME_RESOURCE_PROGS_H_OGRE_MDL,Q1_NAME_RESOURCE_OGRE_OGWAKE_WAV,
     "ogre_stand1", "ogre_walk1", "ogre_run1", "ogre_nail1", 200, -80, LARGE, 0, true},
    {QA_Q1_OGRE, "monster_ogre_rocket", Q1_NAME_RESOURCE_PROGS_OGRE_ROCKET_MDL, Q1_NAME_RESOURCE_PROGS_H_OGRE_MDL,Q1_NAME_RESOURCE_ARMAGON_SIGHT_WAV,
     "ogre_stand1", "ogre_walk1", "ogre_run1", "ogre_nail1", 200, -80, LARGE, 0, true},
    {QA_Q1_HELLKNIGHT, "monster_hell_knight", Q1_NAME_RESOURCE_PROGS_HKNIGHT_MDL, Q1_NAME_RESOURCE_PROGS_H_HELLKN_MDL,Q1_NAME_RESOURCE_HKNIGHT_SIGHT1_WAV,
     "hknight_stand1", "hknight_walk1", "hknight_run1", "hknight_magicc1", 250, -40, HUMAN, 0,
     true},
    {QA_Q1_SHAMBLER, "monster_shambler", Q1_NAME_RESOURCE_PROGS_SHAMBLER_MDL, Q1_NAME_RESOURCE_PROGS_H_SHAMS_MDL,Q1_NAME_RESOURCE_SHAMBLER_SSIGHT_WAV,
     "sham_stand1", "sham_walk1", "sham_run1", "sham_magic1", 600, -60, LARGE, 0, true},
    {QA_Q1_WIZARD, "monster_wizard", Q1_NAME_RESOURCE_PROGS_WIZARD_MDL, Q1_NAME_RESOURCE_PROGS_H_WIZARD_MDL,Q1_NAME_RESOURCE_WIZARD_WSIGHT_WAV,
     "wiz_stand1", "wiz_walk1", "wiz_run1", "wiz_fast1", 80, -40, HUMAN, QA_PHYSICS_FLYING, false},
    {QA_Q1_SHALRATH, "monster_shalrath", Q1_NAME_RESOURCE_PROGS_SHALRATH_MDL, Q1_NAME_RESOURCE_PROGS_H_SHAL_MDL,Q1_NAME_RESOURCE_SHALRATH_SIGHT_WAV,
     "shal_stand", "shal_walk1", "shal_run1", "shal_attack1", 400, -90, LARGE, 0, false},
    {QA_Q1_TARBABY, "monster_tarbaby", Q1_NAME_RESOURCE_PROGS_TARBABY_MDL, Q1_NAME_COUNT,Q1_NAME_RESOURCE_BLOB_SIGHT1_WAV, "tbaby_stand1",
     "tbaby_walk1", "tbaby_run1", "tbaby_jump1", 80, -INFINITY, HUMAN, 0, true},
    {QA_Q1_FISH,
     "monster_fish",
     Q1_NAME_RESOURCE_PROGS_FISH_MDL, Q1_NAME_COUNT,Q1_NAME_RESOURCE_FISH_IDLE_WAV,
     "f_stand1",
     "f_walk1",
     "f_run1",
     NULL,
     25,
     -INFINITY,
     {{-16, -16, -24}, {16, 16, 24}},
     QA_PHYSICS_SWIMMING,
     true},
    {QA_Q1_ZOMBIE, "monster_zombie", Q1_NAME_RESOURCE_PROGS_ZOMBIE_MDL, Q1_NAME_RESOURCE_PROGS_H_ZOMBIE_MDL,Q1_NAME_RESOURCE_ZOMBIE_Z_IDLE_WAV,
     "zombie_stand1", "zombie_walk1", "zombie_run1", "zombie_atta1", 60, 0, HUMAN, 0, false},
    {QA_Q1_BOSS,
     "monster_boss",
     Q1_NAME_RESOURCE_PROGS_BOSS_MDL, Q1_NAME_COUNT,Q1_NAME_RESOURCE_BOSS1_SIGHT1_WAV,
     "boss_idle1",
     "boss_idle1",
     "boss_missile1",
     "boss_missile1",
     3,
     -INFINITY,
     {{-128, -128, -24}, {128, 128, 256}},
     0,
     false},
    {QA_Q1_OLDONE,
     "monster_oldone",
     Q1_NAME_RESOURCE_PROGS_OLDONE_MDL, Q1_NAME_COUNT,Q1_NAME_RESOURCE_BOSS2_SIGHT_WAV,
     "old_idle1",
     "old_idle1",
     "old_idle1",
     NULL,
     40000,
     -INFINITY,
     {{-160, -128, -24}, {160, 128, 256}},
     0,
     false},
    {QA_Q1_EEL,
     "monster_eel",
     Q1_NAME_RESOURCE_PROGS_EEL2_MDL, Q1_NAME_RESOURCE_PROGS_EELGIB_MDL,Q1_NAME_RESOURCE_EEL_EELC5_WAV,
     "eel_stand1",
     "eel_walk1",
     "eel_run1",
     NULL,
     60,
     -12,
     {{-16, -16, -24}, {16, 16, 32}},
     QA_PHYSICS_SWIMMING,
     true},
    {QA_Q1_SWORD, "monster_sword", Q1_NAME_RESOURCE_PROGS_SWORD_MDL, Q1_NAME_COUNT,Q1_NAME_RESOURCE_KNIGHT_KSIGHT_WAV, "sword_stand1",
     "sword_stand1", "sword_run1", NULL, 150, -INFINITY, HUMAN, 0, true},
    {QA_Q1_MUMMY,
     "monster_mummy",
     Q1_NAME_RESOURCE_PROGS_MUMMY_MDL, Q1_NAME_RESOURCE_PROGS_H_ZOMBIE_MDL,Q1_NAME_RESOURCE_ZOMBIE_Z_IDLE_WAV,
     "mummy_stand1",
     "mummy_walk1",
     "mummy_run1",
     "mummy_missile",
     500,
     0,
     {{-16, -16, -24}, {16, 16, 32}},
     0,
     false},
    {QA_Q1_SCOURGE, "monster_scourge", Q1_NAME_RESOURCE_PROGS_SCOR_MDL, Q1_NAME_RESOURCE_PROGS_H_SCOURG_MDL,Q1_NAME_RESOURCE_SCOURGE_SIGHT_WAV,
     "scourge_stand1", "scourge_walk1", "scourge_run1", "scourge_atk1", 300, -35, LARGE, 0, true},
    {QA_Q1_DECOY,
     "monster_decoy",
     Q1_NAME_RESOURCE_PROGS_PLAYER_MDL, Q1_NAME_COUNT,Q1_NAME_CLASS_EMPTY,
     "decoy_stand1",
     "decoy_walk1",
     "decoy_walk1",
     "decoy_stand1",
     3000000,
     -INFINITY,
     {{-16, -16, -24}, {16, 16, 32}},
     0,
     false},
    {QA_Q1_WRATH,
     "monster_wrath",
     Q1_NAME_RESOURCE_PROGS_WRATH_MDL, Q1_NAME_COUNT,Q1_NAME_RESOURCE_WRATH_WSEE_WAV,
     "wrath_stand1",
     "wrath_walk01",
     "wrath_run01",
     "wrath_attack",
     400,
     -INFINITY,
     {{-16, -16, -24}, {16, 16, 32}},
     QA_PHYSICS_FLYING,
     false},
    {QA_Q1_LAVA_MAN, "monster_lava_man", Q1_NAME_RESOURCE_PROGS_LAVAMAN_MDL, Q1_NAME_COUNT,Q1_NAME_CLASS_EMPTY, "lavaman_idle1",
     "lavaman_walk1", "lavaman_walk1", "lavaman_fire1", 1500, -INFINITY, LARGE, 0, true},
    {QA_Q1_SUPER_WRATH,
     "monster_super_wrath",
     Q1_NAME_RESOURCE_PROGS_S_WRATH_MDL, Q1_NAME_COUNT,Q1_NAME_CLASS_EMPTY,
     "overlord_stand1",
     "overlord_walk01",
     "overlord_run01",
     "overlord_missile",
     1000,
     -INFINITY,
     {{-16, -16, -24}, {16, 16, 32}},
     QA_PHYSICS_FLYING,
     true},
    {QA_Q1_GREMLIN,
     "monster_gremlin",
     Q1_NAME_RESOURCE_PROGS_GREM_MDL, Q1_NAME_RESOURCE_PROGS_H_GREM_MDL,Q1_NAME_RESOURCE_GREM_SIGHT1_WAV,
     "gremlin_stand1",
     "gremlin_walk1",
     "gremlin_run1",
     "Gremlin_MissileAttack",
     100,
     -35,
     {{-16, -16, -24}, {16, 16, 32}},
     0,
     true},
    {QA_Q1_ARMAGON,
     "monster_armagon",
     Q1_NAME_RESOURCE_PROGS_ARMALEGS_MDL, Q1_NAME_COUNT,Q1_NAME_RESOURCE_ARMAGON_SIGHT_WAV,
     "armagon_stand1",
     "armagon_walk1",
     "armagon_run1",
     "armagon_missile_attack",
     2500,
     -INFINITY,
     {{-48, -48, -24}, {48, 48, 84}},
     0,
     true},
    {QA_Q1_DRAGON, "monster_dragon", Q1_NAME_RESOURCE_PROGS_DRAGON_MDL, Q1_NAME_COUNT,Q1_NAME_RESOURCE_DRAGON_SEE_WAV, "dragon_walk1",
     "dragon_walk1", "dragon_walk1", NULL, 4000, -INFINITY, LARGE, QA_PHYSICS_FLYING, false},
    {QA_Q1_MORPH,
     "monster_morph",
     Q1_NAME_RESOURCE_PROGS_MORPH_AZ_MDL, Q1_NAME_COUNT,Q1_NAME_CLASS_EMPTY,
     "morph_stand1",
     "morph_walk1",
     "morph_run1",
     "morph_fire1",
     2000,
     -INFINITY,
     {{-16, -16, -24}, {16, 16, 32}},
     0,
     true}};
#undef HUMAN
#undef LARGE

const q1_species *q1_species_find(const char *classname) {
    for (size_t i = 0; i < sizeof(species) / sizeof(*species); ++i)
        if (!strcmp(classname, species[i].classname))
            return &species[i];
    return NULL;
}
