#include "internal.h"

#define HUMAN {{-16, -16, -24}, {16, 16, 40}}
#define LARGE {{-32, -32, -24}, {32, 32, 64}}
static const q1_species species[] = {
    {QA_Q1_ARMY,
     "monster_ghost",
     "progs/player.mdl",
     NULL,
     "",
     "ghost_stand1",
     "ghost_run1",
     "ghost_run1",
     NULL,
     10,
     -INFINITY,
     {{-16, -16, -24}, {16, 16, 32}},
     0,
     false},
    {QA_Q1_WIZARD, "monster_orb", "progs/teleporter_eye_blink.mdl", NULL, "", "orb_stand1",
     "orb_walk1", "orb_run1", "orb_fast1", 300, -INFINITY, LARGE, QA_PHYSICS_FLYING, false},
    {QA_Q1_ZOMBIE,
     "monster_szombie",
     "progs/zombie.mdl",
     NULL,
     "",
     "szombie_stand1",
     "szombie_walk1",
     "szombie_run1",
     NULL,
     60,
     -INFINITY,
     {{-16, -16, -24}, {16, 16, 32}},
     0,
     true},
    {QA_Q1_SHAMBLER, "monster_super_shambler", "progs/shambler_blood.mdl", "h_shams", "",
     "supsham_stand1", "supsham_walk1", "supsham_run1", "supsham_melee", 2000, -60, LARGE, 0, true},
    {QA_Q1_HELLKNIGHT, "monster_ranged_knight", "progs/rknight.mdl", "h_hellkn", "",
     "rknight_stand1", "rknight_walk1", "rknight_run", "rknight_magic", 250, -40, HUMAN, 0, false},
    {QA_Q1_ARMY, "monster_army_infected", "progs/soldier.mdl", "h_guard", "soldier/sight1.wav",
     "infected_army_stand1", "infected_army_walk1", "infected_army_run1", "infected_army_atk1", 30,
     -35, HUMAN, 0, false},
    {QA_Q1_KNIGHT, "monster_knight_infected", "progs/knight.mdl", "h_knight", "knight/ksight.wav",
     "knight_stand1", "knight_walk1", "knight_run1", NULL, 75, -40, HUMAN, 0, true},
    {QA_Q1_ENFORCER, "monster_enforcer_infected", "progs/enforcer.mdl", "h_mega",
     "enforcer/sight1.wav", "enf_stand1", "enf_walk1", "enf_run1", "enf_atk1", 80, -35, LARGE, 0,
     false},
    {QA_Q1_HELLKNIGHT, "monster_hell_knight_infected", "progs/hknight.mdl", "h_hellkn",
     "hknight/sight1.wav", "hknight_stand1", "hknight_walk1", "hknight_run1", "hknight_magicc1",
     250, -40, LARGE, 0, true},
    {QA_Q1_DOG, "monster_demodog", "progs/dog_explosive.mdl", "h_dog", "dog/dsight.wav",
     "demodog_stand1", "demodog_walk1", "demodog_run1", "demodog_leap1", 25, -35, LARGE, 0, true},
    {QA_Q1_ARMY, "monster_army", "progs/soldier.mdl", "h_guard", "soldier/sight1.wav",
     "army_stand1", "army_walk1", "army_run1", "army_atk1", 30, -35, HUMAN, 0, false},
    {QA_Q1_DOG,
     "monster_dog",
     "progs/dog.mdl",
     "h_dog",
     "dog/dsight.wav",
     "dog_stand1",
     "dog_walk1",
     "dog_run1",
     "dog_leap1",
     25,
     -35,
     {{-32, -32, -24}, {32, 32, 40}},
     0,
     true},
    {QA_Q1_KNIGHT, "monster_knight", "progs/knight.mdl", "h_knight", "knight/ksight.wav",
     "knight_stand1", "knight_walk1", "knight_run1", NULL, 75, -40, HUMAN, 0, true},
    {QA_Q1_ENFORCER, "monster_enforcer", "progs/enforcer.mdl", "h_mega", "enforcer/sight1.wav",
     "enf_stand1", "enf_walk1", "enf_run1", "enf_atk1", 80, -35, HUMAN, 0, false},
    {QA_Q1_DEMON, "monster_demon1", "progs/demon.mdl", "h_demon", "demon/sight2.wav",
     "demon1_stand1", "demon1_walk1", "demon1_run1", "demon1_jump1", 300, -80, LARGE, 0, true},
    {QA_Q1_OGRE, "monster_ogre", "progs/ogre.mdl", "h_ogre", "ogre/ogwake.wav", "ogre_stand1",
     "ogre_walk1", "ogre_run1", "ogre_nail1", 200, -80, LARGE, 0, true},
    {QA_Q1_OGRE, "monster_ogre_marksman", "progs/ogre.mdl", "h_ogre", "ogre/ogwake.wav",
     "ogre_stand1", "ogre_walk1", "ogre_run1", "ogre_nail1", 200, -80, LARGE, 0, true},
    {QA_Q1_OGRE, "monster_ogre_rocket", "progs/ogre_rocket.mdl", "h_ogre", "armagon/sight.wav",
     "ogre_stand1", "ogre_walk1", "ogre_run1", "ogre_nail1", 200, -80, LARGE, 0, true},
    {QA_Q1_HELLKNIGHT, "monster_hell_knight", "progs/hknight.mdl", "h_hellkn", "hknight/sight1.wav",
     "hknight_stand1", "hknight_walk1", "hknight_run1", "hknight_magicc1", 250, -40, HUMAN, 0,
     true},
    {QA_Q1_SHAMBLER, "monster_shambler", "progs/shambler.mdl", "h_shams", "shambler/ssight.wav",
     "sham_stand1", "sham_walk1", "sham_run1", "sham_magic1", 600, -60, LARGE, 0, true},
    {QA_Q1_WIZARD, "monster_wizard", "progs/wizard.mdl", "h_wizard", "wizard/wsight.wav",
     "wiz_stand1", "wiz_walk1", "wiz_run1", "wiz_fast1", 80, -40, HUMAN, QA_PHYSICS_FLYING, false},
    {QA_Q1_SHALRATH, "monster_shalrath", "progs/shalrath.mdl", "h_shal", "shalrath/sight.wav",
     "shal_stand", "shal_walk1", "shal_run1", "shal_attack1", 400, -90, LARGE, 0, false},
    {QA_Q1_TARBABY, "monster_tarbaby", "progs/tarbaby.mdl", NULL, "blob/sight1.wav", "tbaby_stand1",
     "tbaby_walk1", "tbaby_run1", "tbaby_jump1", 80, -INFINITY, HUMAN, 0, true},
    {QA_Q1_FISH,
     "monster_fish",
     "progs/fish.mdl",
     NULL,
     "fish/idle.wav",
     "f_stand1",
     "f_walk1",
     "f_run1",
     NULL,
     25,
     -INFINITY,
     {{-16, -16, -24}, {16, 16, 24}},
     QA_PHYSICS_SWIMMING,
     true},
    {QA_Q1_ZOMBIE, "monster_zombie", "progs/zombie.mdl", "h_zombie", "zombie/z_idle.wav",
     "zombie_stand1", "zombie_walk1", "zombie_run1", "zombie_atta1", 60, 0, HUMAN, 0, false},
    {QA_Q1_BOSS,
     "monster_boss",
     "progs/boss.mdl",
     NULL,
     "boss1/sight1.wav",
     "boss_idle1",
     "boss_idle1",
     "boss_missile1",
     "boss_missile1",
     3,
     -INFINITY,
     {{-128, -128, -24}, {128, 128, 256}},
     0,
     false},
    {QA_Q1_OLDONE,
     "monster_oldone",
     "progs/oldone.mdl",
     NULL,
     "boss2/sight.wav",
     "old_idle1",
     "old_idle1",
     "old_idle1",
     NULL,
     40000,
     -INFINITY,
     {{-160, -128, -24}, {160, 128, 256}},
     0,
     false},
    {QA_Q1_EEL,
     "monster_eel",
     "progs/eel2.mdl",
     "eelgib",
     "eel/eelc5.wav",
     "eel_stand1",
     "eel_walk1",
     "eel_run1",
     NULL,
     60,
     -12,
     {{-16, -16, -24}, {16, 16, 32}},
     QA_PHYSICS_SWIMMING,
     true},
    {QA_Q1_SWORD, "monster_sword", "progs/sword.mdl", NULL, "knight/ksight.wav", "sword_stand1",
     "sword_stand1", "sword_run1", NULL, 150, -INFINITY, HUMAN, 0, true},
    {QA_Q1_MUMMY,
     "monster_mummy",
     "progs/mummy.mdl",
     "h_zombie",
     "zombie/z_idle.wav",
     "mummy_stand1",
     "mummy_walk1",
     "mummy_run1",
     "mummy_missile",
     500,
     0,
     {{-16, -16, -24}, {16, 16, 32}},
     0,
     false},
    {QA_Q1_SCOURGE, "monster_scourge", "progs/scor.mdl", "h_scourg", "scourge/sight.wav",
     "scourge_stand1", "scourge_walk1", "scourge_run1", "scourge_atk1", 300, -35, LARGE, 0, true},
    {QA_Q1_DECOY,
     "monster_decoy",
     "progs/player.mdl",
     NULL,
     "",
     "decoy_stand1",
     "decoy_walk1",
     "decoy_walk1",
     "decoy_stand1",
     3000000,
     -INFINITY,
     {{-16, -16, -24}, {16, 16, 32}},
     0,
     false},
    {QA_Q1_WRATH,
     "monster_wrath",
     "progs/wrath.mdl",
     NULL,
     "wrath/wsee.wav",
     "wrath_stand1",
     "wrath_walk01",
     "wrath_run01",
     "wrath_attack",
     400,
     -INFINITY,
     {{-16, -16, -24}, {16, 16, 32}},
     QA_PHYSICS_FLYING,
     false},
    {QA_Q1_LAVA_MAN, "monster_lava_man", "progs/lavaman.mdl", NULL, "", "lavaman_idle1",
     "lavaman_walk1", "lavaman_walk1", "lavaman_fire1", 1500, -INFINITY, LARGE, 0, true},
    {QA_Q1_SUPER_WRATH,
     "monster_super_wrath",
     "progs/s_wrath.mdl",
     NULL,
     "",
     "overlord_stand1",
     "overlord_walk01",
     "overlord_run01",
     "overlord_missile",
     1000,
     -INFINITY,
     {{-16, -16, -24}, {16, 16, 32}},
     QA_PHYSICS_FLYING,
     true},
    {QA_Q1_GREMLIN,
     "monster_gremlin",
     "progs/grem.mdl",
     "h_grem",
     "grem/sight1.wav",
     "gremlin_stand1",
     "gremlin_walk1",
     "gremlin_run1",
     "Gremlin_MissileAttack",
     100,
     -35,
     {{-16, -16, -24}, {16, 16, 32}},
     0,
     true},
    {QA_Q1_ARMAGON,
     "monster_armagon",
     "progs/armalegs.mdl",
     NULL,
     "armagon/sight.wav",
     "armagon_stand1",
     "armagon_walk1",
     "armagon_run1",
     "armagon_missile_attack",
     2500,
     -INFINITY,
     {{-48, -48, -24}, {48, 48, 84}},
     0,
     true},
    {QA_Q1_DRAGON, "monster_dragon", "progs/dragon.mdl", NULL, "dragon/see.wav", "dragon_walk1",
     "dragon_walk1", "dragon_walk1", NULL, 4000, -INFINITY, LARGE, QA_PHYSICS_FLYING, false},
    {QA_Q1_MORPH,
     "monster_morph",
     "progs/morph_az.mdl",
     NULL,
     "",
     "morph_stand1",
     "morph_walk1",
     "morph_run1",
     "morph_fire1",
     2000,
     -INFINITY,
     {{-16, -16, -24}, {16, 16, 32}},
     0,
     true}};
#undef HUMAN
#undef LARGE

const q1_species *q1_species_find(const char *classname) {
    for (size_t i = 0; i < sizeof(species) / sizeof(*species); ++i)
        if (!strcmp(classname, species[i].classname))
            return &species[i];
    return NULL;
}
