#ifndef QA_Q1_WIRE_WORLD_DECLARATIONS_H
#define QA_Q1_WIRE_WORLD_DECLARATIONS_H

/* Official W_Precache/worldspawn resource order. Classic and rerelease
 * Hipnotic/Rogue declarations agree; MG3 and QuakeWorld retain their source tables. */
static const char *const hipnotic_world_sounds[] = {
    "weapons/r_exp3.wav", "weapons/rocket1i.wav", "weapons/sgun1.wav",
    "weapons/guncock.wav", "weapons/ric1.wav", "weapons/ric2.wav",
    "weapons/ric3.wav", "weapons/spike2.wav", "weapons/tink1.wav",
    "weapons/grenade.wav", "weapons/bounce.wav", "weapons/shotgn2.wav",
    "enforcer/enfstop.wav", "knight/sword1.wav", "hipweap/laserg.wav",
    "hipweap/laserric.wav", "hipweap/proxwarn.wav", "hipweap/proxbomb.wav",
    "hipweap/mjolhit.wav", "hipweap/mjolslap.wav", "hipweap/mjoltink.wav",
    "demon/dland2.wav", "misc/h2ohit1.wav", "items/itembk2.wav",
    "player/plyrjmp8.wav", "player/land.wav", "player/land2.wav",
    "player/drown1.wav", "player/drown2.wav", "player/gasp1.wav",
    "player/gasp2.wav", "player/h2odeath.wav", "misc/talk.wav",
    "player/teledth1.wav", "misc/r_tele1.wav", "misc/r_tele2.wav",
    "misc/r_tele3.wav", "misc/r_tele4.wav", "misc/r_tele5.wav",
    "weapons/lock4.wav", "weapons/pkup.wav", "items/armor1.wav",
    "weapons/lhit.wav", "weapons/lstart.wav", "items/damage3.wav",
    "misc/power.wav", "player/gib.wav", "player/udeath.wav",
    "player/tornoff2.wav", "player/pain1.wav", "player/pain2.wav",
    "player/pain3.wav", "player/pain4.wav", "player/pain5.wav",
    "player/pain6.wav", "player/death1.wav", "player/death2.wav",
    "player/death3.wav", "player/death4.wav", "player/death5.wav",
    "weapons/ax1.wav", "player/axhit1.wav", "player/axhit2.wav",
    "player/h2ojump.wav", "player/slimbrn2.wav", "player/inh2o.wav",
    "player/inlava.wav", "misc/outwater.wav", "player/lburn1.wav",
    "player/lburn2.wav", "misc/water1.wav", "misc/water2.wav",
    "misc/flys.wav", "misc/shortexp.wav", "misc/longexpl.wav",
    "misc/foot1.wav", "misc/foot2.wav", "misc/foot3.wav",
    "misc/foot4.wav", "misc/foot5.wav", "misc/foot6.wav",
    "misc/foot7.wav",
};

static const char *const hipnotic_world_models[] = {
    "progs/player.mdl", "progs/eyes.mdl", "progs/h_player.mdl",
    "progs/playham.mdl", "progs/gib1.mdl", "progs/gib2.mdl",
    "progs/gib3.mdl", "progs/s_bubble.spr", "progs/s_explod.spr",
    "progs/v_axe.mdl", "progs/v_shot.mdl", "progs/v_nail.mdl",
    "progs/v_rock.mdl", "progs/v_shot2.mdl", "progs/v_nail2.mdl",
    "progs/v_rock2.mdl", "progs/v_laserg.mdl", "progs/v_hammer.mdl",
    "progs/v_prox.mdl", "progs/proxbomb.mdl", "progs/bolt.mdl",
    "progs/bolt2.mdl", "progs/bolt3.mdl", "progs/lavaball.mdl",
    "progs/lasrspik.mdl", "progs/missile.mdl", "progs/grenade.mdl",
    "progs/spike.mdl", "progs/s_spike.mdl", "progs/backpack.mdl",
    "progs/zom_gib.mdl", "progs/v_light.mdl",
};

static const char *const rogue_world_sounds[] = {
    "weapons/r_exp3.wav", "weapons/rocket1i.wav", "weapons/sgun1.wav",
    "weapons/guncock.wav", "weapons/ric1.wav", "weapons/ric2.wav",
    "weapons/ric3.wav", "weapons/spike2.wav", "weapons/tink1.wav",
    "weapons/grenade.wav", "weapons/bounce.wav", "weapons/shotgn2.wav",
    "weapons/chain1.wav", "pendulum/hit.wav", "lavagun/snail.wav",
    "demon/dland2.wav", "misc/h2ohit1.wav", "items/itembk2.wav",
    "player/plyrjmp8.wav", "player/land.wav", "player/land2.wav",
    "player/drown1.wav", "player/drown2.wav", "player/gasp1.wav",
    "player/gasp2.wav", "player/h2odeath.wav", "misc/talk.wav",
    "player/teledth1.wav", "misc/r_tele1.wav", "misc/r_tele2.wav",
    "misc/r_tele3.wav", "misc/r_tele4.wav", "misc/r_tele5.wav",
    "weapons/lock4.wav", "weapons/pkup.wav", "items/armor1.wav",
    "weapons/lhit.wav", "weapons/lstart.wav", "items/damage3.wav",
    "misc/power.wav", "player/gib.wav", "player/udeath.wav",
    "player/tornoff2.wav", "player/pain1.wav", "player/pain2.wav",
    "player/pain3.wav", "player/pain4.wav", "player/pain5.wav",
    "player/pain6.wav", "player/death1.wav", "player/death2.wav",
    "player/death3.wav", "player/death4.wav", "player/death5.wav",
    "weapons/ax1.wav", "player/axhit1.wav", "player/axhit2.wav",
    "player/h2ojump.wav", "player/slimbrn2.wav", "player/inh2o.wav",
    "player/inlava.wav", "misc/outwater.wav", "player/lburn1.wav",
    "player/lburn2.wav", "misc/water1.wav", "misc/water2.wav",
    "enforcer/enfstop.wav", "plasma/explode.wav", "plasma/flight.wav",
    "plasma/fire.wav", "shield/hit.wav", "belt/use.wav",
    "items/damage2.wav",
};

static const char *const rogue_world_models[] = {
    "progs/player.mdl", "progs/eyes.mdl", "progs/h_player.mdl",
    "progs/gib1.mdl", "progs/gib2.mdl", "progs/gib3.mdl",
    "progs/s_bubble.spr", "progs/s_explod.spr", "progs/v_axe.mdl",
    "progs/v_shot.mdl", "progs/v_nail.mdl", "progs/v_rock.mdl",
    "progs/v_shot2.mdl", "progs/v_nail2.mdl", "progs/v_rock2.mdl",
    "progs/v_lava.mdl", "progs/v_lava2.mdl", "progs/v_multi.mdl",
    "progs/v_multi2.mdl", "progs/bolt.mdl", "progs/bolt2.mdl",
    "progs/bolt3.mdl", "progs/lavaball.mdl", "progs/missile.mdl",
    "progs/grenade.mdl", "progs/spike.mdl", "progs/s_spike.mdl",
    "progs/mervup.mdl", "progs/rockup.mdl", "progs/rockup_d.mdl",
    "progs/lspike.mdl", "progs/shield.mdl", "progs/p_shield.mdl",
    "progs/backpack.mdl", "progs/zom_gib.mdl", "progs/v_light.mdl",
    "progs/plasma.mdl", "progs/v_plasma.mdl", "progs/hook.mdl",
    "progs/v_grpple.mdl",
};

static const char *const mg3_world_sounds[] = {
    "weapons/r_exp3.wav", "weapons/rocket1i.wav", "weapons/sgun1.wav",
    "weapons/guncock.wav", "weapons/ric1.wav", "weapons/ric2.wav",
    "weapons/ric3.wav", "weapons/spike2.wav", "weapons/tink1.wav",
    "weapons/grenade.wav", "weapons/bounce.wav", "weapons/shotgn2.wav",
    "hipweap/laserg.wav", "hipweap/laserric.wav", "enforcer/enfstop.wav",
    "hipweap/mjolslap.wav", "hipweap/mjolhit.wav", "hipweap/mjoltink.wav",
    "hipweap/mjolwam.wav", "demon/dland2.wav", "misc/h2ohit1.wav",
    "items/itembk2.wav", "player/plyrjmp8.wav", "player/land.wav",
    "player/land2.wav", "player/drown1.wav", "player/drown2.wav",
    "player/gasp1.wav", "player/gasp2.wav", "player/h2odeath.wav",
    "misc/talk.wav", "player/teledth1.wav", "misc/r_tele1.wav",
    "misc/r_tele2.wav", "misc/r_tele3.wav", "misc/r_tele4.wav",
    "misc/r_tele5.wav", "weapons/lock4.wav", "weapons/pkup.wav",
    "items/armor1.wav", "weapons/lhit.wav", "weapons/lstart.wav",
    "items/damage3.wav", "misc/power.wav", "player/gib.wav",
    "player/udeath.wav", "player/tornoff2.wav", "player/pain1.wav",
    "player/pain2.wav", "player/pain3.wav", "player/pain4.wav",
    "player/pain5.wav", "player/pain6.wav", "player/death1.wav",
    "player/death2.wav", "player/death3.wav", "player/death4.wav",
    "player/death5.wav", "weapons/ax1.wav", "player/axhit1.wav",
    "player/axhit2.wav", "player/h2ojump.wav", "player/slimbrn2.wav",
    "player/inh2o.wav", "player/inlava.wav", "misc/outwater.wav",
    "player/lburn1.wav", "player/lburn2.wav", "misc/water1.wav",
    "misc/water2.wav",
};

static const char *const mg3_world_models[] = {
    "progs/player.mdl", "progs/eyes.mdl", "progs/h_player.mdl",
    "progs/gib1.mdl", "progs/gib2.mdl", "progs/gib3.mdl",
    "progs/s_bubble.spr", "progs/s_explod.spr", "progs/v_axe.mdl",
    "progs/v_shot.mdl", "progs/v_nail.mdl", "progs/v_rock.mdl",
    "progs/v_shot2.mdl", "progs/v_nail2.mdl", "progs/v_rock2.mdl",
    "progs/bolt.mdl", "progs/bolt2.mdl", "progs/bolt3.mdl",
    "progs/lavaball.mdl", "progs/missile.mdl", "progs/grenade.mdl",
    "progs/spike.mdl", "progs/s_spike.mdl", "progs/backpack.mdl",
    "progs/zom_gib.mdl", "progs/v_light.mdl", "progs/lasrspik.mdl",
    "progs/v_laserg.mdl", "progs/v_hammer.mdl", "progs/v_hammer_glow.mdl",
    "progs/v_bloodshot.mdl", "progs/v_bloodshot2.mdl",
};

static const char *const qw_world_models[] = {
    "progs/player.mdl", "progs/eyes.mdl", "progs/h_player.mdl",
    "progs/gib1.mdl", "progs/gib2.mdl", "progs/gib3.mdl",
    "progs/s_bubble.spr", "progs/s_explod.spr", "progs/v_axe.mdl",
    "progs/v_shot.mdl", "progs/v_nail.mdl", "progs/v_rock.mdl",
    "progs/v_shot2.mdl", "progs/v_nail2.mdl", "progs/v_rock2.mdl",
    "progs/bolt.mdl", "progs/bolt2.mdl", "progs/bolt3.mdl",
    "progs/lavaball.mdl", "progs/missile.mdl", "progs/grenade.mdl",
    "progs/spike.mdl", "progs/s_spike.mdl", "progs/backpack.mdl",
    "progs/zom_gib.mdl", "progs/v_light.mdl",
};
static const char *const qw_world_sounds[] = {
    "weapons/r_exp3.wav", "weapons/rocket1i.wav", "weapons/sgun1.wav",
    "weapons/guncock.wav", "weapons/ric1.wav", "weapons/ric2.wav",
    "weapons/ric3.wav", "weapons/spike2.wav", "weapons/tink1.wav",
    "weapons/grenade.wav", "weapons/bounce.wav", "weapons/shotgn2.wav",
    "demon/dland2.wav", "misc/h2ohit1.wav", "items/itembk2.wav",
    "player/plyrjmp8.wav", "player/land.wav", "player/land2.wav",
    "player/drown1.wav", "player/drown2.wav", "player/gasp1.wav",
    "player/gasp2.wav", "player/h2odeath.wav", "misc/talk.wav",
    "player/teledth1.wav", "misc/r_tele1.wav", "misc/r_tele2.wav",
    "misc/r_tele3.wav", "misc/r_tele4.wav", "misc/r_tele5.wav",
    "weapons/lock4.wav", "weapons/pkup.wav", "items/armor1.wav",
    "weapons/lhit.wav", "weapons/lstart.wav", "items/damage3.wav",
    "misc/power.wav", "player/gib.wav", "player/udeath.wav",
    "player/tornoff2.wav", "player/pain1.wav", "player/pain2.wav",
    "player/pain3.wav", "player/pain4.wav", "player/pain5.wav",
    "player/pain6.wav", "player/death1.wav", "player/death2.wav",
    "player/death3.wav", "player/death4.wav", "player/death5.wav",
    "boss1/sight1.wav", "weapons/ax1.wav", "player/axhit1.wav",
    "player/axhit2.wav", "player/h2ojump.wav", "player/slimbrn2.wav",
    "player/inh2o.wav", "player/inlava.wav", "misc/outwater.wav",
    "player/lburn1.wav", "player/lburn2.wav", "misc/water1.wav",
    "misc/water2.wav", "items/protect.wav", "items/protect2.wav",
    "items/protect3.wav",
};

#endif
