#include "internal.h"

#define COUNT(a) (sizeof(a) / sizeof((a)[0]))
#define TYPE(k) {.kind = (k), .count = 1}
#define ARRAY(k, n) {.kind = (k), .count = (n)}
#define STRUCT(members)                                                                            \
    {.kind = QA_NATIVE_BYTES, .fields = (members), .field_count = COUNT(members), .count = 1}
#define PARAMS(...)                                                                                \
    (const qa_native_type[]) { __VA_ARGS__ }
#define SPEC0(label, index, handler, return_type)                                                           \
    {.name = (label),                                                                              \
     .signature = {.abi = QA_NATIVE_ABI_CDECL_I386,                                                \
                   .parameters = NULL,                                                             \
                   .parameter_count = 0,                                                           \
                   .result = return_type},                                                         \
     .slot = (index), .dispatch = (handler)}
#define SPEC(label, index, handler, return_type, ...)                                                       \
    {.name = (label),                                                                              \
     .signature = {.abi = QA_NATIVE_ABI_CDECL_I386,                                                \
                   .parameters = PARAMS(__VA_ARGS__),                                              \
                   .parameter_count = sizeof(PARAMS(__VA_ARGS__)) / sizeof(qa_native_type),        \
                   .result = return_type},                                                         \
     .slot = (index), .dispatch = (handler)}
#define VARIADIC(label, index, handler, ...)                                                                \
    {.name = (label),                                                                              \
     .signature = {.abi = QA_NATIVE_ABI_CDECL_I386,                                                \
                   .parameters = PARAMS(__VA_ARGS__),                                              \
                   .parameter_count = sizeof(PARAMS(__VA_ARGS__)) / sizeof(qa_native_type),        \
                   .result = TYPE(QA_NATIVE_VOID),                                                 \
                   .variadic = true},                                                              \
     .slot = (index), .dispatch = (handler)}

static const qa_native_type q2_trace_fields[] = {
    TYPE(QA_NATIVE_I32),     TYPE(QA_NATIVE_I32),     TYPE(QA_NATIVE_F32), ARRAY(QA_NATIVE_F32, 3),
    ARRAY(QA_NATIVE_F32, 3), TYPE(QA_NATIVE_F32),     TYPE(QA_NATIVE_U8),  TYPE(QA_NATIVE_U8),
    ARRAY(QA_NATIVE_U8, 2),  TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)};

static const qa_native_type rr_plane_fields[] = {ARRAY(QA_NATIVE_F32, 3), TYPE(QA_NATIVE_F32),
                                                 TYPE(QA_NATIVE_U8), TYPE(QA_NATIVE_U8),
                                                 ARRAY(QA_NATIVE_U8, 2)};

static const qa_native_type rr_trace_fields[] = {
    TYPE(QA_NATIVE_U8),      TYPE(QA_NATIVE_U8),      TYPE(QA_NATIVE_F32), ARRAY(QA_NATIVE_F32, 3),
    STRUCT(rr_plane_fields), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_U32), TYPE(QA_NATIVE_ADDRESS),
    STRUCT(rr_plane_fields), TYPE(QA_NATIVE_ADDRESS)};

static const qa_native_type rr_vec2_fields[] = {TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_F32)};

static const qa_native_type rr_rect_fields[] = {TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
                                                TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)};

static const native_signature_spec q2_imports[] = {
    VARIADIC("bprintf", 0, QA_NATIVE_Q2_IMPORT_bprintf, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    VARIADIC("dprintf", 1, QA_NATIVE_Q2_IMPORT_dprintf, TYPE(QA_NATIVE_ADDRESS)),
    VARIADIC("cprintf", 2, QA_NATIVE_Q2_IMPORT_cprintf, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    VARIADIC("centerprintf", 3, QA_NATIVE_Q2_IMPORT_centerprintf, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("sound", 4, QA_NATIVE_Q2_IMPORT_sound, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_F32)),
    SPEC("positioned_sound", 5, QA_NATIVE_Q2_IMPORT_positioned_sound, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_F32),
         TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_F32)),
    SPEC("configstring", 6, QA_NATIVE_Q2_IMPORT_configstring, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    VARIADIC("error", 7, QA_NATIVE_Q2_IMPORT_error, TYPE(QA_NATIVE_ADDRESS)),
    SPEC("modelindex", 8, QA_NATIVE_Q2_IMPORT_modelindex, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("soundindex", 9, QA_NATIVE_Q2_IMPORT_soundindex, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("imageindex", 10, QA_NATIVE_Q2_IMPORT_imageindex, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("setmodel", 11, QA_NATIVE_Q2_IMPORT_setmodel, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("trace", 12, QA_NATIVE_Q2_IMPORT_trace, STRUCT(q2_trace_fields), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32)),
    SPEC("pointcontents", 13, QA_NATIVE_Q2_IMPORT_pointcontents, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("inPVS", 14, QA_NATIVE_Q2_IMPORT_inPVS, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("inPHS", 15, QA_NATIVE_Q2_IMPORT_inPHS, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("SetAreaPortalState", 16, QA_NATIVE_Q2_IMPORT_SetAreaPortalState, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("AreasConnected", 17, QA_NATIVE_Q2_IMPORT_AreasConnected, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("linkentity", 18, QA_NATIVE_Q2_IMPORT_linkentity, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("unlinkentity", 19, QA_NATIVE_Q2_IMPORT_unlinkentity, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BoxEdicts", 20, QA_NATIVE_Q2_IMPORT_BoxEdicts, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("Pmove", 21, QA_NATIVE_Q2_IMPORT_Pmove, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("multicast", 22, QA_NATIVE_Q2_IMPORT_multicast, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("unicast", 23, QA_NATIVE_Q2_IMPORT_unicast, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("WriteChar", 24, QA_NATIVE_Q2_IMPORT_WriteChar, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("WriteByte", 25, QA_NATIVE_Q2_IMPORT_WriteByte, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("WriteShort", 26, QA_NATIVE_Q2_IMPORT_WriteShort, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("WriteLong", 27, QA_NATIVE_Q2_IMPORT_WriteLong, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("WriteFloat", 28, QA_NATIVE_Q2_IMPORT_WriteFloat, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_F32)),
    SPEC("WriteString", 29, QA_NATIVE_Q2_IMPORT_WriteString, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("WritePosition", 30, QA_NATIVE_Q2_IMPORT_WritePosition, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("WriteDir", 31, QA_NATIVE_Q2_IMPORT_WriteDir, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("WriteAngle", 32, QA_NATIVE_Q2_IMPORT_WriteAngle, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_F32)),
    SPEC("TagMalloc", 33, QA_NATIVE_Q2_IMPORT_TagMalloc, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("TagFree", 34, QA_NATIVE_Q2_IMPORT_TagFree, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("FreeTags", 35, QA_NATIVE_Q2_IMPORT_FreeTags, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("cvar", 36, QA_NATIVE_Q2_IMPORT_cvar, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32)),
    SPEC("cvar_set", 37, QA_NATIVE_Q2_IMPORT_cvar_set, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("cvar_forceset", 38, QA_NATIVE_Q2_IMPORT_cvar_forceset, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC0("argc", 39, QA_NATIVE_Q2_IMPORT_argc, TYPE(QA_NATIVE_I32)),
    SPEC("argv", 40, QA_NATIVE_Q2_IMPORT_argv, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC0("args", 41, QA_NATIVE_Q2_IMPORT_args, TYPE(QA_NATIVE_ADDRESS)),
    SPEC("AddCommandString", 42, QA_NATIVE_Q2_IMPORT_AddCommandString, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("DebugGraph", 43, QA_NATIVE_Q2_IMPORT_DebugGraph, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_I32))};

static const native_signature_spec q2_entries[] = {
    SPEC0("Init", 0, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID)),
    SPEC0("Shutdown", 1, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID)),
    SPEC("SpawnEntities", 2, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("WriteGame", 3, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("ReadGame", 4, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("WriteLevel", 5, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("ReadLevel", 6, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("ClientConnect", 7, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("ClientBegin", 8, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("ClientUserinfoChanged", 9, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("ClientDisconnect", 10, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("ClientCommand", 11, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("ClientThink", 12, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC0("RunFrame", 13, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID)),
    SPEC0("ServerCommand", 14, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID))};

static const native_signature_spec rr_game_imports[] = {
    SPEC("Broadcast_Print", 0, QA_NATIVE_Q2_IMPORT_Broadcast_Print, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Com_Print", 1, QA_NATIVE_Q2_IMPORT_Com_Print, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Client_Print", 2, QA_NATIVE_Q2_IMPORT_Client_Print, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Center_Print", 3, QA_NATIVE_Q2_IMPORT_Center_Print, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("sound", 4, QA_NATIVE_Q2_IMPORT_sound, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_U8),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_F32)),
    SPEC("positioned_sound", 5, QA_NATIVE_Q2_IMPORT_positioned_sound, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_U8), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_F32),
         TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_F32)),
    SPEC("local_sound", 6, QA_NATIVE_Q2_IMPORT_local_sound, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_U8), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_F32),
         TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_U32)),
    SPEC("configstring", 7, QA_NATIVE_Q2_IMPORT_configstring, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("get_configstring", 8, QA_NATIVE_Q2_IMPORT_get_configstring, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("Com_Error", 9, QA_NATIVE_Q2_IMPORT_Com_Error, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("modelindex", 10, QA_NATIVE_Q2_IMPORT_modelindex, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("soundindex", 11, QA_NATIVE_Q2_IMPORT_soundindex, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("imageindex", 12, QA_NATIVE_Q2_IMPORT_imageindex, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("setmodel", 13, QA_NATIVE_Q2_IMPORT_setmodel, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("trace", 14, QA_NATIVE_Q2_IMPORT_trace, STRUCT(rr_trace_fields), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_U32)),
    SPEC("clip", 15, QA_NATIVE_Q2_IMPORT_clip, STRUCT(rr_trace_fields), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_U32)),
    SPEC("pointcontents", 16, QA_NATIVE_Q2_IMPORT_pointcontents, TYPE(QA_NATIVE_U32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("inPVS", 17, QA_NATIVE_Q2_IMPORT_inPVS, TYPE(QA_NATIVE_U8), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_U8)),
    SPEC("inPHS", 18, QA_NATIVE_Q2_IMPORT_inPHS, TYPE(QA_NATIVE_U8), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_U8)),
    SPEC("SetAreaPortalState", 19, QA_NATIVE_Q2_IMPORT_SetAreaPortalState, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_U8)),
    SPEC("AreasConnected", 20, QA_NATIVE_Q2_IMPORT_AreasConnected, TYPE(QA_NATIVE_U8), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("linkentity", 21, QA_NATIVE_Q2_IMPORT_linkentity, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("unlinkentity", 22, QA_NATIVE_Q2_IMPORT_unlinkentity, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BoxEdicts", 23, QA_NATIVE_Q2_IMPORT_BoxEdicts, TYPE(QA_NATIVE_U64), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_U64), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("multicast", 24, QA_NATIVE_Q2_IMPORT_multicast, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_U8)),
    SPEC("unicast", 25, QA_NATIVE_Q2_IMPORT_unicast, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_U8),
         TYPE(QA_NATIVE_U32)),
    SPEC("WriteChar", 26, QA_NATIVE_Q2_IMPORT_WriteChar, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("WriteByte", 27, QA_NATIVE_Q2_IMPORT_WriteByte, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("WriteShort", 28, QA_NATIVE_Q2_IMPORT_WriteShort, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("WriteLong", 29, QA_NATIVE_Q2_IMPORT_WriteLong, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("WriteFloat", 30, QA_NATIVE_Q2_IMPORT_WriteFloat, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_F32)),
    SPEC("WriteString", 31, QA_NATIVE_Q2_IMPORT_WriteString, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("WritePosition", 32, QA_NATIVE_Q2_IMPORT_WritePosition, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("WriteDir", 33, QA_NATIVE_Q2_IMPORT_WriteDir, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("WriteAngle", 34, QA_NATIVE_Q2_IMPORT_WriteAngle, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_F32)),
    SPEC("WriteEntity", 35, QA_NATIVE_Q2_IMPORT_WriteEntity, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("TagMalloc", 36, QA_NATIVE_Q2_IMPORT_TagMalloc, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_U64), TYPE(QA_NATIVE_I32)),
    SPEC("TagFree", 37, QA_NATIVE_Q2_IMPORT_TagFree, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("FreeTags", 38, QA_NATIVE_Q2_IMPORT_FreeTags, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("cvar", 39, QA_NATIVE_Q2_IMPORT_cvar, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_U32)),
    SPEC("cvar_set", 40, QA_NATIVE_Q2_IMPORT_cvar_set, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("cvar_forceset", 41, QA_NATIVE_Q2_IMPORT_cvar_forceset, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC0("argc", 42, QA_NATIVE_Q2_IMPORT_argc, TYPE(QA_NATIVE_I32)),
    SPEC("argv", 43, QA_NATIVE_Q2_IMPORT_argv, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC0("args", 44, QA_NATIVE_Q2_IMPORT_args, TYPE(QA_NATIVE_ADDRESS)),
    SPEC("AddCommandString", 45, QA_NATIVE_Q2_IMPORT_AddCommandString, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("DebugGraph", 46, QA_NATIVE_Q2_IMPORT_DebugGraph, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_I32)),
    SPEC("GetExtension", 47, QA_NATIVE_Q2_IMPORT_GetExtension, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Bot_RegisterEdict", 48, QA_NATIVE_Q2_IMPORT_Bot_RegisterEdict, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Bot_UnRegisterEdict", 49, QA_NATIVE_Q2_IMPORT_Bot_UnRegisterEdict, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Bot_MoveToPoint", 50, QA_NATIVE_Q2_IMPORT_Bot_MoveToPoint, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_F32)),
    SPEC("Bot_FollowActor", 51, QA_NATIVE_Q2_IMPORT_Bot_FollowActor, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("GetPathToGoal", 52, QA_NATIVE_Q2_IMPORT_GetPathToGoal, TYPE(QA_NATIVE_U8), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Loc_Print", 53, QA_NATIVE_Q2_IMPORT_Loc_Print, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_U64)),
    SPEC("Draw_Line", 54, QA_NATIVE_Q2_IMPORT_Draw_Line, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_U8)),
    SPEC("Draw_Point", 55, QA_NATIVE_Q2_IMPORT_Draw_Point, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_F32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_U8)),
    SPEC("Draw_Circle", 56, QA_NATIVE_Q2_IMPORT_Draw_Circle, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_F32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_U8)),
    SPEC("Draw_Bounds", 57, QA_NATIVE_Q2_IMPORT_Draw_Bounds, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_U8)),
    SPEC("Draw_Sphere", 58, QA_NATIVE_Q2_IMPORT_Draw_Sphere, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_F32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_U8)),
    SPEC("Draw_OrientedWorldText", 59, QA_NATIVE_Q2_IMPORT_Draw_OrientedWorldText, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_F32),
         TYPE(QA_NATIVE_U8)),
    SPEC("Draw_StaticWorldText", 60, QA_NATIVE_Q2_IMPORT_Draw_StaticWorldText, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_U8)),
    SPEC("Draw_Cylinder", 61, QA_NATIVE_Q2_IMPORT_Draw_Cylinder, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_F32),
         TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_U8)),
    SPEC("Draw_Ray", 62, QA_NATIVE_Q2_IMPORT_Draw_Ray, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_F32),
         TYPE(QA_NATIVE_U8)),
    SPEC("Draw_Arrow", 63, QA_NATIVE_Q2_IMPORT_Draw_Arrow, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_F32),
         TYPE(QA_NATIVE_U8)),
    SPEC("ReportMatchDetails_Multicast", 64, QA_NATIVE_Q2_IMPORT_ReportMatchDetails_Multicast, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_U8)),
    SPEC0("ServerFrame", 65, QA_NATIVE_Q2_IMPORT_ServerFrame, TYPE(QA_NATIVE_U32)),
    SPEC("SendToClipBoard", 66, QA_NATIVE_Q2_IMPORT_SendToClipBoard, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Info_ValueForKey", 67, QA_NATIVE_Q2_IMPORT_Info_ValueForKey, TYPE(QA_NATIVE_U64), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_U64)),
    SPEC("Info_RemoveKey", 68, QA_NATIVE_Q2_IMPORT_Info_RemoveKey, TYPE(QA_NATIVE_U8), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Info_SetValueForKey", 69, QA_NATIVE_Q2_IMPORT_Info_SetValueForKey, TYPE(QA_NATIVE_U8), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS))};

static const native_signature_spec rr_game_entries[] = {
    SPEC0("PreInit", 0, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID)),
    SPEC0("Init", 1, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID)),
    SPEC0("Shutdown", 2, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID)),
    SPEC("SpawnEntities", 3, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("WriteGameJson", 4, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_U8), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("ReadGameJson", 5, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("WriteLevelJson", 6, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_U8), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("ReadLevelJson", 7, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC0("CanSave", 8, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_U8)),
    SPEC("ClientChooseSlot", 9, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_U8), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_U64),
         TYPE(QA_NATIVE_U8)),
    SPEC("ClientConnect", 10, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_U8), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_U8)),
    SPEC("ClientBegin", 11, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("ClientUserinfoChanged", 12, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("ClientDisconnect", 13, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("ClientCommand", 14, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("ClientThink", 15, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("RunFrame", 16, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_U8)),
    SPEC0("PrepFrame", 17, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID)),
    SPEC0("ServerCommand", 18, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID)),
    SPEC("Pmove", 19, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("GetExtension", 20, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Bot_SetWeapon", 21, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_U8)),
    SPEC("Bot_TriggerEdict", 22, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Bot_UseItem", 23, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("Bot_GetItemID", 24, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Edict_ForceLookAtPoint", 25, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Bot_PickedUpItem", 26, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_U8), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Entity_IsVisibleToPlayer", 27, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_U8), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("GetShadowLightData", 28, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32))};

static const native_signature_spec rr_cgame_imports[] = {
    SPEC("Com_Print", 0, QA_NATIVE_Q2_IMPORT_Com_Print, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("get_configstring", 1, QA_NATIVE_Q2_IMPORT_get_configstring, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("Com_Error", 2, QA_NATIVE_Q2_IMPORT_Com_Error, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("TagMalloc", 3, QA_NATIVE_Q2_IMPORT_TagMalloc, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_U64), TYPE(QA_NATIVE_I32)),
    SPEC("TagFree", 4, QA_NATIVE_Q2_IMPORT_TagFree, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("FreeTags", 5, QA_NATIVE_Q2_IMPORT_FreeTags, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("cvar", 6, QA_NATIVE_Q2_IMPORT_cvar, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_U32)),
    SPEC("cvar_set", 7, QA_NATIVE_Q2_IMPORT_cvar_set, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("cvar_forceset", 8, QA_NATIVE_Q2_IMPORT_cvar_forceset, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("AddCommandString", 9, QA_NATIVE_Q2_IMPORT_AddCommandString, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("GetExtension", 10, QA_NATIVE_Q2_IMPORT_GetExtension, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC0("CL_FrameValid", 11, QA_NATIVE_Q2_IMPORT_CL_FrameValid, TYPE(QA_NATIVE_U8)),
    SPEC0("CL_FrameTime", 12, QA_NATIVE_Q2_IMPORT_CL_FrameTime, TYPE(QA_NATIVE_F32)),
    SPEC0("CL_ClientTime", 13, QA_NATIVE_Q2_IMPORT_CL_ClientTime, TYPE(QA_NATIVE_U64)),
    SPEC0("CL_ClientRealTime", 14, QA_NATIVE_Q2_IMPORT_CL_ClientRealTime, TYPE(QA_NATIVE_U64)),
    SPEC0("CL_ServerFrame", 15, QA_NATIVE_Q2_IMPORT_CL_ServerFrame, TYPE(QA_NATIVE_I32)),
    SPEC0("CL_ServerProtocol", 16, QA_NATIVE_Q2_IMPORT_CL_ServerProtocol, TYPE(QA_NATIVE_I32)),
    SPEC("CL_GetClientName", 17, QA_NATIVE_Q2_IMPORT_CL_GetClientName, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("CL_GetClientPic", 18, QA_NATIVE_Q2_IMPORT_CL_GetClientPic, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("CL_GetClientDogtag", 19, QA_NATIVE_Q2_IMPORT_CL_GetClientDogtag, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("CL_GetKeyBinding", 20, QA_NATIVE_Q2_IMPORT_CL_GetKeyBinding, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Draw_RegisterPic", 21, QA_NATIVE_Q2_IMPORT_Draw_RegisterPic, TYPE(QA_NATIVE_U8), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Draw_GetPicSize", 22, QA_NATIVE_Q2_IMPORT_Draw_GetPicSize, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("SCR_DrawChar", 23, QA_NATIVE_Q2_IMPORT_SCR_DrawChar, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_U8)),
    SPEC("SCR_DrawPic", 24, QA_NATIVE_Q2_IMPORT_SCR_DrawPic, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("SCR_DrawColorPic", 25, QA_NATIVE_Q2_IMPORT_SCR_DrawColorPic, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("SCR_SetAltTypeface", 26, QA_NATIVE_Q2_IMPORT_SCR_SetAltTypeface, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_U8)),
    SPEC("SCR_DrawFontString", 27, QA_NATIVE_Q2_IMPORT_SCR_DrawFontString, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_U8), TYPE(QA_NATIVE_I32)),
    SPEC("SCR_MeasureFontString", 28, QA_NATIVE_Q2_IMPORT_SCR_MeasureFontString, STRUCT(rr_vec2_fields), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32)),
    SPEC("SCR_FontLineHeight", 29, QA_NATIVE_Q2_IMPORT_SCR_FontLineHeight, TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_I32)),
    SPEC("CL_GetTextInput", 30, QA_NATIVE_Q2_IMPORT_CL_GetTextInput, TYPE(QA_NATIVE_U8), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("CL_GetWarnAmmoCount", 31, QA_NATIVE_Q2_IMPORT_CL_GetWarnAmmoCount, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("Localize", 32, QA_NATIVE_Q2_IMPORT_Localize, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_U64)),
    SPEC("SCR_DrawBind", 33, QA_NATIVE_Q2_IMPORT_SCR_DrawBind, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC0("CL_InAutoDemoLoop", 34, QA_NATIVE_Q2_IMPORT_CL_InAutoDemoLoop, TYPE(QA_NATIVE_U8))};

static const native_signature_spec rr_cgame_entries[] = {
    SPEC0("Init", 0, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID)),
    SPEC0("Shutdown", 1, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID)),
    SPEC("DrawHUD", 2, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         STRUCT(rr_rect_fields), STRUCT(rr_rect_fields), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC0("TouchPics", 3, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID)),
    SPEC("LayoutFlags", 4, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I16), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("GetActiveWeaponWheelWeapon", 5, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("GetOwnedWeaponWheelWeapons", 6, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_U32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("GetWeaponWheelAmmoCount", 7, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I16), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32)),
    SPEC("GetPowerupWheelCount", 8, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I16), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32)),
    SPEC("GetHitMarkerDamage", 9, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I16), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Pmove", 10, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("ParseConfigString", 11, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("ParseCenterPrint", 12, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_U8)),
    SPEC("ClearNotify", 13, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("ClearCenterprint", 14, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("NotifyMessage", 15, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_U8)),
    SPEC("GetMonsterFlashOffset", 16, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_U16),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("GetExtension", 17, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS))};

static const native_signature_spec q3_entries[] = {
    SPEC("vmMain", 0, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32))};

/* Quake Live API 10 passes a sparse 206-slot function-pointer table.  The
 * omitted slots are documented gaps and stay null.  Vector and record
 * parameters are pointers after C array decay; the host reads and writes them
 * through qa_native_read/qa_native_write. */
static const native_signature_spec ql_imports[] = {
    SPEC("SendConsoleCommand", 0, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Printf", 2, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("FS_Write", 4, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32)),
    SPEC("FS_Read", 6, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32)),
    SPEC("FS_FOpenFile", 8, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32)),
    SPEC("FS_FCloseFile", 9, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("Error", 10, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Cvar_VariableValue", 11, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Cvar_Update", 12, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Cvar_VariableStringBuffer", 13, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("Cvar_Set", 15, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Cvar_Register", 17, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("Argv", 18, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32)),
    SPEC0("Argc", 20, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32)),
    SPEC("LocateGameData", 22, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("DropClient", 23, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("SendServerCommand", 24, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("SetConfigstring", 25, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("GetConfigstring", 26, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32)),
    SPEC("GetUserinfo", 28, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32)),
    SPEC("SetUserinfo", 29, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("GetServerinfo", 30, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("SetBrushModel", 31, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("Trace", 32, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("TraceCapsule", 33, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("PointContents", 34, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("AdjustAreaPortalState", 37, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32)),
    SPEC("LinkEntity", 39, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("UnlinkEntity", 40, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("EntitiesInBox", 41, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("EntityContact", 42, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC0("BotAllocateClient", 43, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32)),
    SPEC("BotFreeClient", 44, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("GetUsercmd", 45, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("GetEntityToken", 46, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC0("BotLibSetup", 49, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32)),
    SPEC0("BotLibShutdown", 50, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32)),
    SPEC("BotLibVarSet", 51, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotLibDefine", 53, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotLibStartFrame", 54, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_F32)),
    SPEC("BotLibLoadMap", 55, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotLibUpdateEntity", 56, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotGetSnapshotEntity", 58, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("BotUserCommand", 60, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("AAS_EntityInfo", 63, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC0("AAS_Initialized", 64, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32)),
    SPEC0("AAS_Time", 66, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_F32)),
    SPEC("AAS_PointAreaNum", 67, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("AAS_TraceAreas", 69, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32)),
    SPEC("AAS_PresenceTypeBoundingBox", 70, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("AAS_PointReachabilityAreaIndex", 71, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("AAS_BBoxAreas", 72, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("AAS_AreaInfo", 73, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("AAS_PointContents", 74, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("AAS_NextBSPEntity", 75, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("AAS_ValueForBSPEpairKey", 76, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("AAS_VectorForBSPEpairKey", 77, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("AAS_FloatForBSPEpairKey", 78, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("AAS_IntForBSPEpairKey", 79, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("AAS_AreaReachability", 80, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("AAS_AreaTravelTimeToGoalArea", 81, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("AAS_EnableRoutingArea", 82, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32)),
    SPEC("AAS_PredictRoute", 83, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32)),
    SPEC("AAS_AlternativeRouteGoals", 84, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("AAS_Swimming", 85, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("AAS_PredictClientMovement", 86, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("EA_Command", 87, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("EA_Say", 88, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("EA_SayTeam", 89, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("EA_Action", 90, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("EA_Gesture", 91, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("EA_Talk", 92, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("EA_Attack", 93, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("EA_Use", 94, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("EA_Respawn", 95, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("EA_MoveUp", 96, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("EA_MoveDown", 97, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("EA_MoveForward", 98, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("EA_MoveBack", 99, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("EA_MoveLeft", 100, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("EA_MoveRight", 101, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("EA_Crouch", 102, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("EA_SelectWeapon", 103, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("EA_Jump", 104, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("EA_DelayedJump", 105, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("EA_Move", 106, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_F32)),
    SPEC("EA_View", 107, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("EA_EndRegular", 108, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_F32)),
    SPEC("EA_GetInput", 109, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_F32),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("EA_ResetInput", 110, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("BotLoadCharacter", 111, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_F32)),
    SPEC("BotFreeCharacter", 112, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("Characteristic_Float", 113, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32)),
    SPEC("Characteristic_BFloat", 114, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_F32)),
    SPEC("Characteristic_Integer", 115, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32)),
    SPEC("Characteristic_BInteger", 116, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("Characteristic_String", 117, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC0("BotAllocChatState", 118, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32)),
    SPEC("BotFreeChatState", 119, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("BotQueueConsoleMessage", 120, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotRemoveConsoleMessage", 121, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32)),
    SPEC("BotNextConsoleMessage", 122, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotNumConsoleMessages", 123, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("BotInitialChat", 124, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotNumInitialChats", 125, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotReplyChat", 126, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotChatLength", 127, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("BotEnterChat", 128, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32)),
    SPEC("BotGetChatMessage", 129, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("StringContains", 130, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("BotFindMatch", 131, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotMatchVariable", 132, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("UnifyWhiteSpaces", 133, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotReplaceSynonyms", 134, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotSetChatGender", 135, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("BotSetChatName", 136, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32)),
    SPEC("BotLoadChatFile", 137, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotResetGoalState", 138, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("BotResetAvoidGoals", 139, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("BotRemoveFromAvoidGoals", 140, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32)),
    SPEC("BotPushGoal", 141, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotPopGoal", 142, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("BotEmptyGoalStack", 143, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("BotDumpAvoidGoals", 144, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("BotDumpGoalStack", 145, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("BotGoalName", 146, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32)),
    SPEC("BotGetTopGoal", 147, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotGetSecondGoal", 148, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotChooseLTGItem", 149, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("BotChooseNBGItem", 150, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_F32)),
    SPEC("BotTouchingGoal", 151, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotItemGoalInVisButNotVisible", 152, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotGetLevelItemGoal", 153, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotGetNextCampSpotGoal", 154, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotGetMapLocationGoal", 155, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotAvoidGoalTime", 156, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("BotSetAvoidGoalTime", 157, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_F32)),
    SPEC0("BotInitLevelItems", 158, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID)),
    SPEC0("BotUpdateEntityItems", 159, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID)),
    SPEC("BotLoadItemWeights", 160, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotFreeItemWeights", 161, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("BotInterbreedGoalFuzzyLogic", 162, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("BotSaveGoalFuzzyLogic", 163, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotMutateGoalFuzzyLogic", 164, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_F32)),
    SPEC("BotAllocGoalState", 165, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("BotFreeGoalState", 166, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("BotResetMoveState", 167, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("BotMoveToGoal", 168, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("BotMoveInDirection", 169, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_I32)),
    SPEC("BotResetAvoidReach", 170, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("BotResetLastAvoidReach", 171, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("BotReachabilityArea", 172, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32)),
    SPEC("BotMovementViewTarget", 173, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_F32),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotPredictVisiblePosition", 174, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC0("BotAllocMoveState", 175, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32)),
    SPEC("BotFreeMoveState", 176, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("BotInitMoveState", 177, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotAddAvoidSpot", 178, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_F32), TYPE(QA_NATIVE_I32)),
    SPEC("BotChooseBestFightWeapon", 179, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotGetWeaponInfo", 180, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotLoadWeaponWeights", 181, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC0("BotAllocWeaponState", 182, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32)),
    SPEC("BotFreeWeaponState", 183, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("BotResetWeaponState", 184, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("GeneticParentsAndChildSelection", 185, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS)),
    SPEC("BotGetServerCommand", 186, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32)),
    SPEC("BotLibVarGet", 187, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32)),
    SPEC("BotLibTest", 188, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("PC_LoadSource", 189, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("PC_FreeSource", 190, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("PC_ReadToken", 191, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("PC_SourceFileAndLine", 192, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS)),
    SPEC("GetSteamID", 200, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_U64), TYPE(QA_NATIVE_I32)),
    SPEC("GetServerSteamID", 202, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_ADDRESS),
         TYPE(QA_NATIVE_I32)),
    SPEC("IncrementSteamStat", 203, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("GetSteamStat", 204, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32)),
    SPEC("VerifySteamAuth", 205, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32))};

static const native_signature_spec ql_entries[] = {
    SPEC("Shutdown", 0, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("RunFrame", 1, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC0("RegisterCvars", 2, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID)),
    SPEC("Init", 3, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32)),
    SPEC0("ConsoleCommand", 4, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_I32)),
    SPEC("ClientUserinfoChanged", 5, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("ClientThink", 6, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("ClientDisconnect", 7, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32)),
    SPEC("ClientConnect", 8, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_I32), TYPE(QA_NATIVE_I32),
         TYPE(QA_NATIVE_I32)),
    SPEC("ClientCommand", 9, QA_NATIVE_Q2_IMPORT_NONE, TYPE(QA_NATIVE_VOID), TYPE(QA_NATIVE_I32))};

static const native_profile_spec profiles[] = {
    {QA_NATIVE_Q2_GAME_API3, "GetGameAPI", 3, q2_imports, COUNT(q2_imports), q2_entries,
     COUNT(q2_entries), 0, 15, true, false, false},
    {QA_NATIVE_Q2_GAME_API2023, "GetGameAPI", 2023, rr_game_imports, COUNT(rr_game_imports),
     rr_game_entries, COUNT(rr_game_entries), 16, 19, true, false, false},
    {QA_NATIVE_Q2_CGAME_API2023, "GetCGameAPI", 2022, rr_cgame_imports, COUNT(rr_cgame_imports),
     rr_cgame_entries, COUNT(rr_cgame_entries), 16, SIZE_MAX, true, false, false},
    {QA_NATIVE_Q3_VMMAIN, "dllEntry", 8, NULL, 0, q3_entries, COUNT(q3_entries), 0, SIZE_MAX, false,
     true, false},
    {QA_NATIVE_QUAKE_LIVE_GAME_API10, "dllEntry", 10, ql_imports, COUNT(ql_imports), ql_entries,
     COUNT(ql_entries), 0, SIZE_MAX, false, false, true}};

const native_profile_spec *native_profile(qa_native_profile profile) {
    for (size_t index = 0; index < COUNT(profiles); ++index)
        if (profiles[index].profile == profile)
            return &profiles[index];
    return NULL;
}

qa_native_q2_import_kind qa_native_q2_import_dispatch(qa_native_profile profile,uint32_t slot)
{
    switch (profile) {
    case QA_NATIVE_Q2_GAME_API3: return slot<COUNT(q2_imports)?q2_imports[slot].dispatch:QA_NATIVE_Q2_IMPORT_NONE;
    case QA_NATIVE_Q2_GAME_API2023: return slot<COUNT(rr_game_imports)?rr_game_imports[slot].dispatch:QA_NATIVE_Q2_IMPORT_NONE;
    case QA_NATIVE_Q2_CGAME_API2023: return slot<COUNT(rr_cgame_imports)?rr_cgame_imports[slot].dispatch:QA_NATIVE_Q2_IMPORT_NONE;
    default: return QA_NATIVE_Q2_IMPORT_NONE;
    }
}

bool native_profile_accepts(const native_profile_spec *profile, const qa_native_image_info *image,
                            qa_error *error) {
    if (!profile || !image)
        return native_fail(error, QA_ERROR_ARGUMENT, 0,
                           "native profile and image metadata are required");
    switch (profile->profile) {
    case QA_NATIVE_Q2_GAME_API3:
        if (image->target.arch == QA_NATIVE_ARCH_I386 ||
            (image->format == QA_NATIVE_IMAGE_ELF64 && image->target.arch == QA_NATIVE_ARCH_X86_64))
            return true;
        return native_fail(error, QA_ERROR_UNSUPPORTED, 0,
                           "Q2 API 3 requires an i386 image or a native x86-64 ELF rebuild");
    case QA_NATIVE_Q2_GAME_API2023:
    case QA_NATIVE_Q2_CGAME_API2023:
        if (image->target.arch == QA_NATIVE_ARCH_X86_64 &&
            (image->format == QA_NATIVE_IMAGE_PE32_PLUS || image->format == QA_NATIVE_IMAGE_ELF64))
            return true;
        return native_fail(error, QA_ERROR_UNSUPPORTED, 0,
                           "Q2 API 2023 requires an x86-64 PE or ELF image");
    case QA_NATIVE_Q3_VMMAIN:
        if (image->target.arch == QA_NATIVE_ARCH_I386 &&
            (image->format == QA_NATIVE_IMAGE_PE32 || image->format == QA_NATIVE_IMAGE_ELF32))
            return true;
        return native_fail(error, QA_ERROR_UNSUPPORTED, 0,
                           "Q3 1.32 native vmMain requires an i386 PE or ELF image");
    case QA_NATIVE_QUAKE_LIVE_GAME_API10:
        if ((image->target.arch == QA_NATIVE_ARCH_I386 && image->format == QA_NATIVE_IMAGE_ELF32) ||
            (image->target.arch == QA_NATIVE_ARCH_X86_64 && image->format == QA_NATIVE_IMAGE_ELF64))
            return true;
        return native_fail(error, QA_ERROR_UNSUPPORTED, 0,
                           "Quake Live API 10 requires an i386 or x86-64 ELF image");
    }
    return native_fail(error, QA_ERROR_ARGUMENT, 0, "unknown native profile");
}

static bool write_pointer(void *table, size_t offset, uint64_t pointer, size_t width) {
    if (width == 4) qa_store_u32le((uint8_t *)table + offset, (uint32_t)pointer);
    else qa_store_u64le((uint8_t *)table + offset, pointer);
    return true;
}

static size_t q2_entry_offset(const qa_native_instance *instance, uint32_t slot) {
    size_t pointer_bytes = instance->module->info.image.target.pointer_bytes;
    size_t offset = native_align(sizeof(int32_t), pointer_bytes);
    if (instance->module->info.profile != QA_NATIVE_Q2_GAME_API2023 || slot < 19)
        return offset + (size_t)slot * pointer_bytes;
    offset += 19u * pointer_bytes;
    offset += pointer_bytes * 2u + sizeof(uint32_t) * 3u;
    offset = native_align(offset, pointer_bytes);
    return offset + (size_t)(slot - 19u) * pointer_bytes;
}

static bool read_pointer(const qa_native_instance *instance, qa_native_address address,
    qa_native_address *out, qa_error *error) {
    uint8_t pointer[8]; size_t width = instance->module->info.image.target.pointer_bytes;
    if (!qa_native_read(instance, address, pointer, width, error))
        return false;
    *out = width == 4 ? qa_load_u32le(pointer) : qa_load_u64le(pointer);
    return true;
}

static bool publish_import_table(qa_native_instance *instance, qa_error *error)
{
    return qa_native_guest_allocate(instance->guest, instance->import_table_bytes,
        INT32_C(0x4e494d50), &instance->import_table_address, error) &&
        qa_native_guest_write(instance->guest, instance->import_table_address,
            (qa_bytes){instance->import_table, instance->import_table_bytes}, error);
}

bool native_profile_restore_tables(qa_native_instance *instance, qa_error *error)
{
    const native_profile_spec *profile = native_profile(instance->module->info.profile);
    if (!profile->q2_table) return true;
    int32_t api;
    if (!qa_native_read(instance, instance->export_table, &api, sizeof(api), error)) return false;
    if (api != (int32_t)profile->api_version)
        return native_fail(error, QA_ERROR_FORMAT, instance->export_table,
                           "restored native Q2 SDK API differs from its actual profile");
    if (profile->import_prefix) {
        uint8_t actual[16], expected[16] = {0};
        qa_store_u32le(expected, instance->options.tick_rate);
        qa_store_f32le(expected + 4, instance->options.frame_seconds);
        qa_store_u32le(expected + 8, instance->options.frame_milliseconds);
        if (profile->import_prefix != sizeof(actual) ||
            !qa_native_read(instance, instance->import_table_address, actual, sizeof(actual), error))
            return false;
        if (memcmp(actual, expected, sizeof(actual)))
            return native_fail(error, QA_ERROR_FORMAT, instance->import_table_address,
                               "restored native Q2 SDK clock differs from its actual declaration");
    }
    size_t width = instance->module->info.image.target.pointer_bytes;
    for (size_t i = 0; i < instance->import_count; ++i) {
        size_t offset = profile->import_prefix + i * width;
        qa_native_address address;
        if (offset > UINT64_MAX - instance->import_table_address)
            return native_fail(error, QA_ERROR_FORMAT, i, "restored native SDK import address overflows");
        if (!read_pointer(instance, instance->import_table_address + offset, &address, error)) return false;
        if (address != instance->imports[i].guest_address)
            return native_fail(error, QA_ERROR_FORMAT, i,
                               "restored native Q2 SDK import lost its retained callback");
    }
    for (size_t i = 0; i < instance->entry_count; ++i) {
        const native_entry_binding *entry = instance->entries + i;
        size_t offset = q2_entry_offset(instance, entry->spec.slot);
        qa_native_address address;
        if (offset > UINT64_MAX - instance->export_table)
            return native_fail(error, QA_ERROR_FORMAT, i, "restored native SDK export address overflows");
        if (!read_pointer(instance, instance->export_table + offset, &address, error)) return false;
        if (address != entry->address)
            return native_fail(error, QA_ERROR_FORMAT, entry->spec.slot,
                               "restored native Q2 SDK entry differs from its retained source table");
    }
    qa_native_entity_table saved = instance->entities;
    if (!native_profile_refresh_entities(instance, error)) return false;
    if (saved.base != instance->entities.base || saved.stride != instance->entities.stride ||
        saved.count != instance->entities.count || saved.capacity != instance->entities.capacity)
        return native_fail(error, QA_ERROR_FORMAT, instance->export_table,
                           "restored native Q2 entity extent differs from its retained SDK table");
    return true;
}

static bool bind_q2_table(qa_native_instance *instance, const native_profile_spec *profile,
                          qa_error *error) {
    size_t pointer_bytes = instance->module->info.image.target.pointer_bytes;
    size_t pointer_region;
    if (!native_size_multiply(profile->import_count, pointer_bytes, &pointer_region) ||
        !native_size_add(profile->import_prefix, pointer_region, &instance->import_table_bytes))
        return native_fail(error, QA_ERROR_MEMORY, 0, "native import table size overflow");
    instance->import_table = calloc(1, instance->import_table_bytes);
    instance->imports = calloc(profile->import_count, sizeof(*instance->imports));
    if (!instance->import_table || (profile->import_count && !instance->imports))
        return native_fail(error, QA_ERROR_MEMORY, 0, "allocating native import table");
    instance->import_count = profile->import_count;
    if (profile->import_prefix) {
        memcpy(instance->import_table, &instance->options.tick_rate,
               sizeof(instance->options.tick_rate));
        memcpy((uint8_t *)instance->import_table + 4, &instance->options.frame_seconds,
               sizeof(instance->options.frame_seconds));
        memcpy((uint8_t *)instance->import_table + 8, &instance->options.frame_milliseconds,
               sizeof(instance->options.frame_milliseconds));
    }
    for (size_t index = 0; index < profile->import_count; ++index) {
        if (!native_import_bind(&instance->imports[index], instance,
                                &profile->imports[index], error)) return false;
        uint64_t address = instance->imports[index].guest_address;
        write_pointer(instance->import_table, profile->import_prefix + index * pointer_bytes, address, pointer_bytes);
    }
    if (!publish_import_table(instance, error)) return false;
    qa_native_address get_api;
    if (!qa_native_export(instance, profile->entry_export, &get_api, error))
        return false;
    qa_native_type get_parameters[] = {TYPE(QA_NATIVE_ADDRESS)};
    qa_native_signature get_signature = {.abi = instance->module->info.image.target.abi,
                                         .parameters = get_parameters,
                                         .parameter_count = 1,
                                         .result = TYPE(QA_NATIVE_ADDRESS)};
    qa_native_value argument = {.type = QA_NATIVE_ADDRESS,
                                .as.address = instance->import_table_address};
    qa_native_value result = {0};
    bool ok =
        native_process_invoke(instance, get_api, &get_signature, &argument, 1, &result, error);
    if (!ok)
        return false;
    if (!result.as.address)
        return native_fail(error, QA_ERROR_FORMAT, 0, "native Q2 API returned a null export table");
    instance->export_table = result.as.address;
    int32_t api_version;
    if (!qa_native_read(instance, instance->export_table, &api_version, sizeof(api_version), error))
        return false;
    if (api_version != (int32_t)profile->api_version) {
        qa_error_set(error, QA_ERROR_UNSUPPORTED, 0, "native Q2 module reports API %d; expected %u",
                     api_version, profile->api_version);
        return false;
    }
    instance->entries = calloc(profile->entry_count, sizeof(*instance->entries));
    if (profile->entry_count && !instance->entries)
        return native_fail(error, QA_ERROR_MEMORY, 0, "allocating native export bindings");
    instance->entry_count = profile->entry_count;
    for (size_t index = 0; index < profile->entry_count; ++index) {
        native_entry_binding *binding = &instance->entries[index];
        binding->spec = profile->entries[index];
        binding->spec.signature.abi = instance->module->info.image.target.abi;
        qa_native_address at =
            instance->export_table + q2_entry_offset(instance, binding->spec.slot);
        if (!read_pointer(instance, at, &binding->address, error))
            return false;
        if (!binding->address && !binding->spec.optional) {
            qa_error_set(error, QA_ERROR_FORMAT, binding->spec.slot, "native Q2 export %s is null",
                         binding->spec.name);
            return false;
        }
    }
    return native_profile_refresh_entities(instance, error);
}

static bool bind_q3(qa_native_instance *instance, const native_profile_spec *profile,
                    qa_error *error) {
    qa_native_address dll_entry, vm_main;
    if (!qa_native_export(instance, "dllEntry", &dll_entry, error) ||
        !qa_native_export(instance, "vmMain", &vm_main, error))
        return false;
    qa_native_type parameter[] = {TYPE(QA_NATIVE_ADDRESS)};
    qa_native_signature signature = {.abi = instance->module->info.image.target.abi,
                                     .parameters = parameter,
                                     .parameter_count = 1,
                                     .result = TYPE(QA_NATIVE_VOID)};
    qa_native_value argument = {.type = QA_NATIVE_ADDRESS};
    if (!native_process_q3_bind(instance, &argument.as.address, error)) return false;
    bool ok =
        native_process_invoke(instance, dll_entry, &signature, &argument, 1, NULL, error);
    if (!ok)
        return false;
    instance->entries = calloc(1, sizeof(*instance->entries));
    if (!instance->entries)
        return native_fail(error, QA_ERROR_MEMORY, 0, "allocating native Q3 entry binding");
    instance->entry_count = 1;
    instance->entries[0].spec = profile->entries[0];
    instance->entries[0].spec.signature.abi = instance->module->info.image.target.abi;
    instance->entries[0].address = vm_main;
    return true;
}

static bool bind_ql(qa_native_instance *instance, const native_profile_spec *profile,
                    qa_error *error) {
    enum { QL_IMPORT_SLOTS = 206 };
    size_t pointer_bytes = instance->module->info.image.target.pointer_bytes;
    if (!native_size_multiply(QL_IMPORT_SLOTS, pointer_bytes, &instance->import_table_bytes))
        return native_fail(error, QA_ERROR_MEMORY, 0, "Quake Live import table size overflow");
    instance->import_table = calloc(1, instance->import_table_bytes);
    instance->imports = calloc(profile->import_count, sizeof(*instance->imports));
    if (!instance->import_table || !instance->imports)
        return native_fail(error, QA_ERROR_MEMORY, 0, "allocating Quake Live import table");
    instance->import_count = profile->import_count;
    for (size_t index = 0; index < profile->import_count; ++index) {
        const native_signature_spec *spec = &profile->imports[index];
        if (spec->slot >= QL_IMPORT_SLOTS)
            return native_fail(error, QA_ERROR_FORMAT, spec->slot,
                               "Quake Live import slot is outside API 10");
        if (!native_import_bind(&instance->imports[index], instance, spec, error))
            return false;
        write_pointer(instance->import_table, (size_t)spec->slot * pointer_bytes,
            instance->imports[index].guest_address, pointer_bytes);
    }
    if (!publish_import_table(instance, error)) return false;

    qa_native_address dll_entry;
    if (!qa_native_export(instance, profile->entry_export, &dll_entry, error))
        return false;
    qa_native_address exports = 0;
    int32_t api_version = 0;
    qa_native_type parameters[] = {TYPE(QA_NATIVE_ADDRESS), TYPE(QA_NATIVE_ADDRESS),
                                   TYPE(QA_NATIVE_ADDRESS)};
    qa_native_signature signature = {.abi = instance->module->info.image.target.abi,
                                     .parameters = parameters,
                                     .parameter_count = COUNT(parameters),
                                     .result = TYPE(QA_NATIVE_VOID)};
    qa_native_value arguments[] = {
        {.type = QA_NATIVE_ADDRESS},
        {.type = QA_NATIVE_ADDRESS,
         .as.address = instance->import_table_address},
        {.type = QA_NATIVE_ADDRESS}};
    uint64_t scratch = 0;
    if (!qa_native_guest_allocate(instance->guest, pointer_bytes + 4, INT32_C(0x4e414249), &scratch, error)) return false;
    arguments[0].as.address = scratch; arguments[2].as.address = scratch + pointer_bytes;
    bool ok = native_process_invoke(instance, dll_entry, &signature, arguments,
                              COUNT(arguments), NULL, error);
    if (scratch) {
        qa_native_address actual_exports = 0;
        if (ok) ok = read_pointer(instance, scratch, &actual_exports, error) &&
            qa_native_read(instance, scratch + pointer_bytes, &api_version, 4, error);
        exports = actual_exports;
        qa_error cleanup = {0};
        if (!qa_native_guest_free(instance->guest, scratch, &cleanup) && ok) { if (error) *error = cleanup; ok = false; }
    }
    if (!ok)
        return false;
    if (api_version != (int32_t)profile->api_version) {
        qa_error_set(error, QA_ERROR_UNSUPPORTED, 0,
                     "Quake Live module reports API %d; expected %u", api_version,
                     profile->api_version);
        return false;
    }
    if (!exports)
        return native_fail(error, QA_ERROR_FORMAT, 0,
                           "Quake Live dllEntry returned a null export table");
    instance->export_table = exports;
    instance->entries = calloc(profile->entry_count, sizeof(*instance->entries));
    if (!instance->entries)
        return native_fail(error, QA_ERROR_MEMORY, 0, "allocating Quake Live export bindings");
    instance->entry_count = profile->entry_count;
    for (size_t index = 0; index < profile->entry_count; ++index) {
        native_entry_binding *binding = &instance->entries[index];
        binding->spec = profile->entries[index];
        binding->spec.signature.abi = instance->module->info.image.target.abi;
        qa_native_address at =
            instance->export_table + (uint64_t)binding->spec.slot * pointer_bytes;
        if (!read_pointer(instance, at, &binding->address, error))
            return false;
        if (!binding->address) {
            qa_error_set(error, QA_ERROR_FORMAT, binding->spec.slot, "Quake Live export %s is null",
                         binding->spec.name);
            return false;
        }
    }
    return true;
}

bool native_profile_bind(qa_native_instance *instance, qa_error *error) {
    const native_profile_spec *profile = native_profile(instance->module->info.profile);
    if (!profile)
        return native_fail(error, QA_ERROR_ARGUMENT, 0, "unknown native module profile");
    if (profile->q2_table)
        return bind_q2_table(instance, profile, error);
    if (profile->q3_vm)
        return bind_q3(instance, profile, error);
    if (profile->quake_live)
        return bind_ql(instance, profile, error);
    return native_fail(error, QA_ERROR_ARGUMENT, 0, "native profile has no binding strategy");
}

bool native_profile_prepare_tables(qa_native_instance *instance, qa_error *error) {
    const native_profile_spec *profile =
        instance ? native_profile(instance->module->info.profile) : NULL;
    if (!profile)
        return native_fail(error, QA_ERROR_ARGUMENT, 0, "native process profile is invalid");
    instance->entries = calloc(profile->entry_count, sizeof(*instance->entries));
    if (profile->entry_count && !instance->entries)
        return native_fail(error, QA_ERROR_MEMORY, 0,
                           "allocating native process entry descriptions");
    instance->entry_count = profile->entry_count;
    for (size_t index = 0; index < profile->entry_count; ++index) {
        instance->entries[index].spec = profile->entries[index];
        instance->entries[index].spec.signature.abi = instance->module->info.image.target.abi;
    }
    return true;
}

void native_profile_unbind(qa_native_instance *instance) {
    if (!instance)
        return;
    for (size_t index = 0; index < instance->import_count; ++index)
        native_import_unbind(&instance->imports[index]);
    free(instance->entries);
    free(instance->imports);
    free(instance->import_table);
    instance->entries = NULL;
    instance->imports = NULL;
    instance->import_table = NULL;
    instance->entry_count = instance->import_count = 0;
    instance->import_table_bytes = 0;
    instance->export_table = 0;
}

const native_entry_binding *native_entry(const qa_native_instance *instance, const char *name) {
    if (!instance || !name)
        return NULL;
    for (size_t index = 0; index < instance->entry_count; ++index)
        if (!strcmp(instance->entries[index].spec.name, name))
            return &instance->entries[index];
    return NULL;
}

bool native_profile_refresh_entities(qa_native_instance *instance, qa_error *error) {
    qa_native_profile profile = instance->module->info.profile;
    if (profile == QA_NATIVE_Q2_CGAME_API2023 || profile == QA_NATIVE_Q3_VMMAIN ||
        profile == QA_NATIVE_QUAKE_LIVE_GAME_API10)
        return true;
    if (!instance->export_table)
        return native_fail(error, QA_ERROR_ARGUMENT, 0, "native Q2 export table is unavailable");
    size_t pointer_bytes = instance->module->info.image.target.pointer_bytes;
    size_t fields = native_align(sizeof(int32_t), pointer_bytes);
    fields += (profile == QA_NATIVE_Q2_GAME_API3 ? 15u : 19u) * pointer_bytes;
    qa_native_entity_table table = {0};
    if (!read_pointer(instance, instance->export_table + fields, &table.base, error))
        return false;
    fields += pointer_bytes;
    if (profile == QA_NATIVE_Q2_GAME_API3) {
        int32_t stride, count, capacity;
        if (!qa_native_read(instance, instance->export_table + fields, &stride, sizeof(stride), error) ||
            !qa_native_read(instance, instance->export_table + fields + 4u, &count, sizeof(count),
                                error) ||
            !qa_native_read(instance, instance->export_table + fields + 8u, &capacity, sizeof(capacity),
                                error))
            return false;
        if (stride < 0 || count < 0 || capacity < 0) {
            return native_fail(error, QA_ERROR_FORMAT, fields,
                               "native Q2 entity metadata is negative");
        }
        table.stride = (size_t)stride;
        table.count = (uint32_t)count;
        table.capacity = (uint32_t)capacity;
    } else {
        uint64_t stride;
        if (!qa_native_read(instance, instance->export_table + fields, &stride, sizeof(stride), error) ||
            !qa_native_read(instance, instance->export_table + fields + 8u, &table.count,
                                sizeof(table.count), error) ||
            !qa_native_read(instance, instance->export_table + fields + 12u, &table.capacity,
                                sizeof(table.capacity), error))
            return false;
#if SIZE_MAX < UINT64_MAX
        if (stride > (uint64_t)SIZE_MAX)
            return native_fail(error, QA_ERROR_FORMAT, fields,
                               "native Q2 entity stride exceeds the host");
#endif
        table.stride = (size_t)stride;
    }
    qa_error publication = {0};
    if (!native_entity_table_store(instance, table, &publication)) {
        if (publication.code == QA_ERROR_ARGUMENT)
            return native_fail(error, QA_ERROR_FORMAT, fields,
                               "invalid native Q2 entity table metadata");
        if (publication.code == QA_ERROR_MEMORY)
            return native_fail(error, QA_ERROR_MEMORY, 0,
                               "allocating native source slot bindings");
        if (error) *error = publication;
        return false;
    }
    return true;
}

#undef COUNT
#undef TYPE
#undef ARRAY
#undef STRUCT
#undef PARAMS
#undef SPEC0
#undef SPEC
#undef VARIADIC
