#ifndef QA_NATIVE_WIRE_CONSTANTS_H
#define QA_NATIVE_WIRE_CONSTANTS_H

#define NATIVE_WIRE_MAGIC 0x524e4151u
#define NATIVE_WIRE_VERSION 2u
#define NATIVE_WIRE_REPLY 0x8000u
#define NATIVE_WIRE_REPLY_BYTES_OVERHEAD 28u

typedef enum native_wire_opcode {
    NATIVE_WIRE_LOAD = 1,
    NATIVE_WIRE_CALL,
    NATIVE_WIRE_INVOKE,
    NATIVE_WIRE_EXPORT,
    NATIVE_WIRE_READ,
    NATIVE_WIRE_WRITE,
    NATIVE_WIRE_ALLOCATE,
    NATIVE_WIRE_FREE,
    NATIVE_WIRE_FREE_TAG,
    NATIVE_WIRE_ENTITY_GET,
    NATIVE_WIRE_ENTITY_SET,
    NATIVE_WIRE_CHECKPOINT_CAPTURE,
    NATIVE_WIRE_CHECKPOINT_RESTORE,
    NATIVE_WIRE_DESTROY,
    NATIVE_WIRE_IMPORT = 64,
    NATIVE_WIRE_DESCRIBE_SYSCALL,
    NATIVE_WIRE_SYSCALL,
    NATIVE_WIRE_HOST_CHECKPOINT,
    NATIVE_WIRE_HOST_RESTORE,
    NATIVE_WIRE_REGION
} native_wire_opcode;

#endif
