#!/usr/bin/env python3
"""Generate common renderer mode metadata from the authored Source tables."""
import argparse
import csv
import re
from pathlib import Path


def modes(path, symbol):
    match = re.search(r'\b' + symbol + r'\[\]\s*=\s*\{(.*?)\n\};', path.read_text(), re.S)
    if not match:
        raise ValueError('Source mode table is absent: ' + str(path))
    return [(int(width), int(height)) for width, height in
            re.findall(r'\{\s*"[^"]+"\s*,\s*(\d+)\s*,\s*(\d+)\s*,', match[1])]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument('--source-root', type=Path)
    parser.add_argument('--check', action='store_true')
    options = parser.parse_args()
    source = options.source_root or options.root.parent / 'qsrc'
    with (options.root / 'data/unified-cvars.csv').open(newline='') as stream:
        rows = {row['canonical']: row for row in csv.DictReader(stream)}
    mode = rows['r_mode']
    if 'mode tables differ' not in mode['conversion'].lower():
        raise ValueError('Mode conversion no longer declares Source resolution tables')
    aliases = [name for name, profiles in re.findall(r'([A-Za-z_][A-Za-z_0-9]*)\(([^)]*)\)', mode['aliases'])
               if 'Q2' in profiles.split(',')]
    classic = modes(source / 'quake-2/linux/vid_so.c', 'vid_modes')
    arena = modes(source / 'quake-iii-arena/code/renderer/tr_init.c', 'r_vidModes')
    if not classic or not arena or classic != arena[:len(classic)] or not aliases:
        raise ValueError('Q2 and Q3 Source modes no longer share their authored prefix')
    fullscreen = re.findall(r'([A-Za-z_][A-Za-z_0-9]*)\(([^)]*)\)', rows['r_fullscreen']['aliases'])
    fullscreen = [name for name, profiles in fullscreen if 'Q2R' in profiles.split(',')]
    if len(fullscreen) != 1:
        raise ValueError('Fullscreen conversion requires its actual Q2R member')
    text = '''#ifndef QA_FRONTEND_VIDEO_MODES_GENERATED_H
#define QA_FRONTEND_VIDEO_MODES_GENERATED_H
#include <stdint.h>
/* Generated by tools/generate_video_modes.py from data/unified-cvars.csv,
 * quake-2/linux/vid_so.c and quake-iii-arena/code/renderer/tr_init.c. */
typedef struct frontend_video_mode_size { uint32_t width,height; } frontend_video_mode_size;
static const frontend_video_mode_size frontend_video_modes[]={
'''
    text += ''.join('    {%d,%d},\n' % pair for pair in arena)
    text += '};\n#define FRONTEND_Q2_VIDEO_MODE_COUNT %du\n' % len(classic)
    text += '#define FRONTEND_VIDEO_MODE_NAME "%s"\n' % mode['canonical']
    text += '#define FRONTEND_VIDEO_FULLSCREEN_MEMBER "%s"\n' % fullscreen[0]
    text += 'static const char *const frontend_q2_video_members[]={'
    text += ','.join('"' + name + '"' for name in aliases) + '};\n#endif\n'
    target = options.root / 'src/app/frontend/video_modes_generated.h'
    if options.check:
        if not target.exists() or target.read_text() != text:
            raise SystemExit('Generated video modes differ: ' + str(target))
    else:
        target.write_text(text)
    print('Source video mode metadata matches' if options.check else 'Generated Source video mode metadata')


if __name__ == '__main__':
    main()
